### ISSUE TITLE
P3 Generic Script Updating Requirement

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#10]
Any edited scripts need to be checked to ensure that `Write-Output` is replaced with `Write-Host` and that every command line whose output is not captured to a variable is piped using ` |Out-Default | Write-Host `. Ref: Appendix: Generic Script Updating Requirement

**Comment by VarunChopraAccolite** [comment]
`| Out-Host` should also be replaced with `| Out-Default | Write-Host`

**Comment by VarunChopraAccolite** [comment]
`Out-Default | Write-Host | Write-Verbose` should also be replaced with `Out-Default | Write-Host`

**Comment by VarunChopraAccolite** [comment]
Hi @robe070 
The changes are checked in. Please let me know if anything further is required and we can close this issue.
