### ISSUE TITLE
Azure Template CD Pipeline increase parallelism

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#105]
Each stack requires three ips and the maximum is 40 in a region. There are 13 separate stacks so running them all parallel would consume 39 ips which is too close to the limit given other stacks may already exist.

So, increase the maximum number of ips (Architect) and then split up the pipeline into 1 stack creation per stage.

**Comment by ganeshk146** [comment]
The changes are done in the below pipelines
1. https://dev.azure.com/VisualLansa/Lansa%20Azure%20Scalable%20License%20Images/_releaseDefinition?definitionId=17&_a=environments-editor-preview

2. https://dev.azure.com/VisualLansa/Lansa%20Azure%20Scalable%20License%20Images/_releaseDefinition?definitionId=16&_a=environments-editor-preview

from my side no changes left for this ticket

**Comment by ganeshk146** [comment]
Testing has been done on  these releases
https://dev.azure.com/VisualLansa/Lansa%20Azure%20Scalable%20License%20Images/_releaseProgress?_a=release-pipeline-progress&releaseId=219

https://dev.azure.com/VisualLansa/Lansa%20Azure%20Scalable%20License%20Images/_releaseProgress?_a=release-pipeline-progress&releaseId=224
