### ISSUE TITLE
Add test for both Image and Template that Amazon SSM Agent is running

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#111]
Amazon SSM Agent running is mandatory for the LANSA license to be valid. And an issue occurred when it wasn't running and it was complex to identify. So catch it upfront.

When testing the version is correct, also test this. This occurs in many tests in the pipelines.

Must be written as a Powershell script file.

**Comment by robe070** [comment]
I have fixed this. Can't wait for your slow work.

CheckAWSSSmAgent.ps1 has invalid text in it. Here is a hex view. They are not even valid UTF-8 or utf-16 combinations, even if reversed. Strangely, Visual Code does not show these corruptions and neither does Notepad++. I used Notepad++ hex view plugin to see the issue. You'll need something similar in order to effectively fix this:
![image](https://user-images.githubusercontent.com/4089160/125006130-c1752080-e0a0-11eb-861a-dedf3c152451.png)

Please fix this ASAP. You will need to run the Template CI pipeline to see the error or use your

**Comment by rizwancel** [comment]
I have removed the invalid characters which is listed in below images.
![invalid_char](https://user-images.githubusercontent.com/38536632/125083681-4f272f00-e0e6-11eb-9387-ab08bc8fd53b.JPG)
