### ISSUE TITLE
Azure Image CD jobs to delete stacks at the start of the job

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#113]
Bring the Azure Image CD pipeline in line with the newer pipelines which delete the stack at the beginning of the job. Both the Preview Tests and the Published tests need to be changed.

**Comment by Arshpreet1002** [comment]
Which pipeline should I work and which stacks to be deleted.

**Comment by robe070** [comment]
[Azure Image Release 2.0](https://dev.azure.com/VisualLansa/Lansa%20Azure%20Scalable%20License%20Images/_releaseDefinition?definitionId=15&_a=environments-editor-preview)

Compare the `AUS IMG Test` stages with the `PrevTest` and `ProdTest` stages. You'll see that Delete Resource Group is the 3rd task in the `AUS IMG Test` stages and it does not exist in the other 2. So create the tasks to do a similar thing. Ensure it does not fail if the RG does not exist which it won't if the previous run of the stage succeeded. A good way to repro is to wait for the `Deploy ARM Template` task to create the RG and then cancel the stage. Then re-deploy it and ensure it gets removed.

**Comment by Arshpreet1002** [comment]
I have made the required changes and Tested the pipeline that is working fine but failing at some other stage.
This is the Test Release Link.
https://dev.azure.com/VisualLansa/Lansa%20Azure%20Scalable%20License%20Images/_apps/hub/ms.vss-releaseManagement-web.cd-release-progress?releaseId=212&_a=release-pipeline-progress

**Comment by robe070** [comment]
The cause is because there are manual steps when the cookbooks debug/paas branch needs to be merged to patch/paas, and then another pone to merge patch/paas into support/scalable.

I have done the first merge. The 2nd one can't be done until the images have been pushed into production because existing users will would then be using old images with new code.

For your purposes, failing is actually a GOOD thing. That means the stack is still there and needs to be deleted by your code. So, I have restarted all the Stages. The PrevTest ones should now succeed completely. The ProdTest should successfully delete the stack, re-create it and fail on the test because the script is missing from the support/scalable branch.

**Comment by robe070** [comment]
The deletion is not working. Thats why the PrevTest Stages are still not finding the script - because the stack is not re-created. In the following image you can see that the deletion takes just 15 seconds when a more typical time might be 15 minutes. And the stack creation is about 1 minute when its normally more like 1 hour. So please work out why the deletion is not working.

![image](https://user-images.githubusercontent.com/4089160/125748311-efbb245d-f4b2-49e4-8a86-51e4d2918dfc.png)

**Comment by Arshpreet1002** [comment]
I have Created a RG in portal and then again ran the PrevTest stage ,So its deleting the Rg and The Stage is also getting succeeded.I am attaching the link to the pipeline.

https://dev.azure.com/VisualLansa/Lansa%20Azure%20Scalable%20License%20Images/_releaseProgress?releaseId=212&_a=release-environment-logs&environmentId=2659#

**Comment by robe070** [comment]
What did you change? You said you did that before, and it clearly is not deleting the RG.

I think you are not deleting the correct RG. Because there was no need for you to create one because it was already there.

**Comment by robe070** [comment]
I have checked. You are not deleting the correct RG

**Comment by Arshpreet1002** [comment]
[113_screenshots.docx](https://github.com/robe070/cookbooks/files/6840247/113_screenshots.docx)

**Comment by robe070** [comment]
Thank you for the PrevTest. What about the ProdTest?

**Comment by Arshpreet1002** [comment]
Please find the file for both Prod and Prev Tests.
[113_screenshots.docx](https://github.com/robe070/cookbooks/files/6845746/113_screenshots.docx)
