### ISSUE TITLE
AWS Use appropriate MSI urls for v14.2 and v15 images

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#114]
Currently the global variable `LANSAMSIValue` is the only URL used.

Change the name of this **global variable** to `msiURLPrevious` and use this variable name for v14.2 tests = AWAMAPP_v14.2.21217_en-us.msi.
Use this variable for all V14.2 tests which use the template.

Add a new **global variable** named `msiURLLatest` = AWAMAPP_v15.0.21217_en-us.msi.
Use this variable for all V15 tests which use the template.

**Comment by sharirpcs** [comment]
Please review the changes in this pipeline release test release.https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-pipeline-progress&releaseId=511

**Comment by sharirpcs** [comment]
Release-71 has got changes tested.Please review it.
https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_release?view=all&_a=releases&definitionId=6
