### ISSUE TITLE
Change the Shoe Size tests to use the new template

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#115]
This template `lansa-stack-type-win.cfn.template` has been created to replace the 5 shoe size templates:
```
lansa-development-win.cfn.template
lansa-test-win.cfn.template
lansa-small-win.cfn.template
lansa-medium-win.cfn.template
lansa-large-win.cfn.template
```

Replace all tests in the pipelines that refer to any of the above templates to instead refer to the new template `lansa-stack-type-win.cfn.template` and set the StackType parameter to one of either `dev`, `test`, `small`, `medium` and `large` as appropriate.

**Comment by sharirpcs** [comment]
Testing is completed and successful.Please review it https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_release?definitionId=6&view=mine&_a=releases

**Comment by robe070** [comment]
Please provide release url, not pipeline url.

**Comment by sharirpcs** [comment]
Release-71 has got the changes tested.Please review it.
https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_release?view=all&_a=releases&definitionId=6
