### ISSUE TITLE
Fix up the AWS Template CD Pipeline

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#117]
If necessary, refer to #82  for the initial work.

Implement the architecture described in the [wiki](https://github.com/robe070/cookbooks/wiki/AWS-Release-Pipelines-High-Level-View). Individual Issues have been created for each of the stages/jobs/tasks that require changes or are new - see Issues which are labelled `Template Release Pipeline` or this [project ](https://github.com/robe070/cookbooks/projects/10#card-56470241). This task is to ensure that the pipeline as a whole reflects the wiki.

Main concrete task for this issue is to decide which solution to use for entering the AWS Marketplace TemplateUrl.

All tests should be in their own Stage. 1 job per stage creating 1 CF stack and testing it.

**Comment by robe070** [comment]
The last Task in the test stages is often failing and thus halting automatic progress as well as requiring a manual check of why the failure has occurred. See Release-121 https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-pipeline-progress&releaseId=610

This task is not a fundamental part of the test. Its failure is not a failure of the test. Its actually a failure of Azure DevOps.
As such I have attempted to workaround  this by setting the `Continue On Error`. This has not had the desired effect. It does not continue. And the Stage is still flagged as failed.

The deletion of the stack that occurs at the beginning of each stage is hand coded so that failures are not errors. So, please do the following, using the stage `AUS Small Shoe Size w16d-14-2` as an example.

1. Delete the existing `AWS CloudFormation Delete Stack` task at the end of the stage which deletes the stack `Cleanup CFN Template : Small Stack-TemplateTest`
2. Clone the PowerShell Task `Cleanup CFN Template : Small Stack-Template`  move it to the end to replace the deleted task.

This needs to be performed in every stage for the last task which deletes the stack, in the 3 AWS pipelines that use a template - `Template CI`, `Image Release` and `Template Release`.

And in looking at this I've noticed another defect. The stack name is correctly set as a Gate variable, but then is never used. The idea is that as much as possible of each test stage is identical to every other test stage. Thus when cloning one, the smallest amount of change is required. This was stated before, but it has not been implemented that way. So, replace all the references to the stack name, e.g. `$(stacknamesmall)` with the gate variable `$(Gate.stack)`. And then remove the variable that contains the stack name e.g. `stacknamesmall`. The Image Release pipeline has been done correctly.

**Comment by robe070** [comment]
Testing should be done with the LANSA artefacts.

If you need to do testing of git repo commits, then I have a better way to manage the need to change to Celestial Artefacts and changing pipeline variables.
1. For Artefacts, don't delete the LANSA ones. Just change the Source Alias by adding "_LANSA" on the end. Then create a celestial artefact with the original alias name.
2. For variables like `GitCookBooksRepoName`, create a variable group which all pipelines can share and add all the variables in there with the same name. They will be the LANSA repos. Variable Group to be called `LANSA Repositories`. The pipeline variables will override them, if necessary. Then to switch from Celestial back to LANSA all the pipeline variables just need the name changed to <name>_Celestial.

**Comment by ganeshk146** [comment]
@robe070 ,

Please let me know which pipelines I need to change it?

**Comment by robe070** [comment]
Its in my comment

**Comment by robe070** [comment]
> This needs to be performed in every stage for the last task which deletes the stack, in the 3 AWS pipelines that use a template - `Template CI`, `Image Release` and `Template Release`.

**Comment by ganeshk146** [comment]
call Rob?, Just to make sure I understand correctly before doing the changes

**Comment by ganeshk146** [comment]
Hi @robe070 ,

The requested changes are completed on "Template CI, Image Release and Template Release" pipelines, Please review it and confirm, Thanks

**Comment by robe070** [comment]
The stackname must be UNIQUE and be a LITERAL. It must only be specified when setting the Gate.Stack variable. Use a variant of the Stage Name as the Stack name. Then they can be easily associated.

e.g. Stage `w12r2d-14-2 IMG Test ` to have stackname `w12r2d-14-2-IMG`
Stage `w12r2d-14-2 US IMG Test` to have stackname `w12r2d-14-2-US-IMG`
Stage `AUS Small Shoe Size w16d-14-2` to have stackname `AUS-Small`
Stage `Oregon Preview w16d-15-0` to have stackname `Oregon-Preview`
Stage `Canada Prod w19d-15-0` to have stackname `Canada-Prod`

This is incorrect:
-BaseImageName 'w12r2d-14-2' -stackname '$(stackname)'

should be
-BaseImageName 'w12r2d-14-2' -stackname 'w12r2d-14-2-IMG'

Repeat for all the other test stages

ALL stages must have a UNIQUE stack name so they may co-exist.

**Comment by ganeshk146** [comment]
> The stackname must be UNIQUE and be a LITERAL. It must only be specified when setting the Gate.Stack variable. Use a variant of the Stage Name as the Stack name. Then they can be easily associated.
> 
> e.g. Stage `w12r2d-14-2 IMG Test ` to have stackname `w12r2d-14-2-IMG`
> Stage `w12r2d-14-2 US IMG Test` to have stackname `w12r2d-14-2-US-IMG`
> Stage `AUS Small Shoe Size w16d-14-2` to have stackname `AUS-Small`
> Stage `Oregon Preview w16d-15-0` to have stackname `Oregon-Preview`
> Stage `Canada Prod w19d-15-0` to have stackname `Canada-Prod`
> 
> This is incorrect:
> -BaseImageName 'w12r2d-14-2' -stackname '$(stackname)'
> 
> should be
> -BaseImageName 'w12r2d-14-2' -stackname 'w12r2d-14-2-IMG'
> 
> Repeat for all the other test stages
> 
> ALL stages must have a UNIQUE stack name so they may co-exist.

The Changes are done Rob, Please review it.

**Comment by robe070** [comment]
I'll need to check your changes later. 

I've fixed up an issue with the Template CI pipeline and restarted it.

**Comment by robe070** [comment]
Template CI Successful

**Comment by robe070** [comment]
I'm just about to create an AWS Image Release run. I'm only running what you've changed - the template tests. Can you please keep an eye on the status and fix any failures and re-run it the same way please, or at least with no more Stages than this. You could cut them down even more if that suits your purposes.
![image](https://user-images.githubusercontent.com/4089160/129864490-f0d48549-a306-431b-9af8-f48a98964ba0.png)

**Comment by ganeshk146** [comment]
> I'm just about to create an AWS Image Release run. I'm only running what you've changed - the template tests. Can you please keep an eye on the status and fix any failures and re-run it the same way please, or at least with no more Stages than this. You could cut them down even more if that suits your purposes.
> ![image](https://user-images.githubusercontent.com/4089160/129864490-f0d48549-a306-431b-9af8-f48a98964ba0.png)

Sure Rob

**Comment by robe070** [comment]
I have manually deployed all the tests at once. Because the 1155 artefacts have already been through this pipeline, everything is already in place.

**Comment by robe070** [comment]
Ditto for the Template Release pipeline:
![image](https://user-images.githubusercontent.com/4089160/129865565-3a8db51c-803b-4a79-9fae-bc534ea219aa.png)

**Comment by ganeshk146** [comment]
> I have manually deployed all the tests at once. Because the 1155 artefacts have already been through this pipeline, everything is already in place.

There was an error occurred https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-environment-logs&releaseId=611&environmentId=9964 this was due to **space** at the end of the **stack name** and it is fixed now

**Comment by robe070** [comment]
Template Release pipeline.
Many Job not responding errors when deleting the stack. So it has not addressed the issue it was meant to do.
Also, the stack names end up being `-Gatestack w19d-14-2-7-w19d-14-2-Dev-Shoe`. So please remove the version text from the stackname passed to the Gate variable so it receives just `AUS-Dev' in this instance. All of the AUS Stages should start with AUS.

Remove the version text from all the test stages.

And to try and stop the errors when deleting the stack, set these options on each of them:
![image](https://user-images.githubusercontent.com/4089160/130003453-c568a21c-3c33-4d98-b0eb-02ec141efdc8.png)


The rest of my assessment below requires no action...

Japanese failures are OK. The Marketplace templates had to have the JPN removed. **The tests should not have been run.**

`Frankfurt PROD` failure does not seem to be our issue.

`Ireland PROD` was a job not responding issue. Not our problem.

TemplateUrl.txt failure due to not finding the S3 bucket. 3 of them in Hong Kong, Milan and Bahrain. Very strange. All other downloads use the local region and work. I changed these regions to be ap-southeast-2

**Comment by ganeshk146** [comment]
@robe070 ,

The change you made on this release stage is failed due to a timeout error https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-environment-logs&releaseId=614&environmentId=10060

**Comment by robe070** [comment]
I like that at least its a different kind of 'error'. To give it a chance to succeed we need to increase the value beyond the normal time for deletion. My observation of success is within 15 minutes. And it fails if the job takes longer than 18 minutes.

So set the timeout to 17.

Can the timeout be a Variable? If so, please put the variable in a a variable group to be shared by all pipelines.

**Comment by ganeshk146** [comment]
ok let me add 17 and test it, once we get green build I will do the change in the remaining stages by referring timeout variable from variable group

**Comment by ganeshk146** [comment]
Hi @robe070 ,

I added variable **DeleteStackTimeout** and changed in all stages to refer to this variable.

**Comment by ganeshk146** [comment]
@robe070 ,

Please let me know is there anything left out to close this ticket

**Comment by robe070** [comment]
It needs to be tested. First phase had no failures with maximum delete task time of about 17:10.

**Comment by robe070** [comment]
I've tested AWS Template Release as far as I can and it seems better. All deletions succeeded. 2 of them were 17+ minutes.

I made this change to the Templates Release pipeline. Please apply it to the Image Release pipeline too:
![image](https://user-images.githubusercontent.com/4089160/130193378-bbe88079-adf5-4cf5-9a9d-d24225a71aed.png)

When you've made the change run the pipeline as described here https://github.com/robe070/cookbooks/issues/117#issuecomment-900922724

**Comment by robe070** [comment]
Actually, the 120 should be a variable.

**Comment by ganeshk146** [comment]
@robe070 ,

Please confirm the variable name to keep it for 120

**Comment by ganeshk146** [comment]
@robe070 ,

The pipeline is not allowing to make TimeOut a variable
<img width="1226" alt="Screenshot 2021-08-23 at 11 11 13 AM" src="https://user-images.githubusercontent.com/72592790/130396219-bb4ea1b2-de2d-41cf-9c85-6266b25db290.png">

**Comment by ganeshk146** [comment]
@robe070 ,
```
I've tested AWS Template Release as far as I can and it seems better. All deletions succeeded. 2 of them were 17+ minutes.

I made this change to the Templates Release pipeline. 
```
This has been done and running the pipeline https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-pipeline-progress&releaseId=622

**Comment by robe070** [comment]
Please use a literal value of 120

**Comment by ganeshk146** [comment]
Changes are done and running the pipeline https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-pipeline-progress&releaseId=623
