### ISSUE TITLE
New Task Update AUS AMI Mappings

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#119]
Take the master template in the `support/scalable` branch and update the `ap-southeast-2`  entries in the 2 mapping tables with the AMI ids from the Image CI artifacts. Use a Powershell script saved in the `lansa/aws-templates` repo in a `scripts` directory

Add task to `S3 template upload` job.

Also add JPN image base names to array of image base names. They are the same as the English names but with a `j` appended to the base name. Only Win2016 and Win2019. There are no Japanese images for Win2012.

The full Japanese AWS image version names may be found here: https://github.com/robe070/cookbooks/issues/136#issuecomment-816415477

**Comment by robe070** [comment]
The name of the parameter will be `ImageType` and will be a string with a `ValidateSet`
It will take these values only: `Development`, `Publication`.

`Development` for this Issue. 
`Production` for Issue #121

**Comment by robe070** [comment]
I notice that the Stages named `Publish <ImageBaseName> AMI to US ` have a task `Add Name Tag` which writes out the copied AMI names to the file `copy-<ImageBaseName>.txt` and that file is then copied to S3 by the following task `S3 Upload AMI file`

So I may have given you unnecessary instructions in the Review meeting yesterday. 

And I'm not clear that you are receiving these comments, so please acknowledge in this thread.

**Comment by rizwancel** [comment]
Committed a new powershell script which gets AMI IDs based on Production/Devlopment image type and then sets appropriate region type and updates JSON template file with proper AMI IDs.

**Comment by ganeshk146** [comment]
@robe070 ,

I added the steps as per today's discussion in the morning.
Here is the pipeline which commits the changes to `feature/tamplate_id` (temp branch) https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-environment-logs&releaseId=303&environmentId=4220

Here is the pipeline which merges the changes from `feature/tamplate_id` to `feature/119` (for testing purpose only need to changes it to support/scalable) 
https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-environment-logs&releaseId=304&environmentId=4247

**Comment by robe070** [comment]
@ganeshk146 Changes to the pipeline look correct. The formatting of the template is so different that its not simple to compare before and after versions. And you'll need to revert the change to feature/119 branch before running another test.
@rizwancel Formatting of the template after updating the AMIs is wrong. This must be corrected ASAP. Release-97 seems to be showing that the template is invalid too.
