### ISSUE TITLE
New Job Commit AUS template changes

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#120]
**Commit AUS template changes**: 
Commits the master template changes to the `aws-templates` git repo in `support/scalable` branch and pushes changes to GitHub. New job `Commit AMI Changes` that has all the `Publish *` jobs as prereqs (These changes now become the default images for all template tests in `ap-southeast-2`)
(Note the preview jobs need to be deleted)

Refer to the Wiki for suggestions on how to commit changes in the pipeline: https://github.com/robe070/cookbooks/wiki/AWS-Release-Pipelines-High-Level-View

Use a Powershell script saved in the `lansa/aws-templates` repo in a `scripts` directory

**Comment by robe070** [comment]
If the code is extremely simple like 
```
git commit
git push
```
then inline would be OK. Anything more complex then a script file is required.

**Comment by ganeshk146** [comment]
@robe070 ,  just taking a step back to understand few things
- which file we need to commit to the GitHub repo?
- if we are running the pipeline with our feature branch it will commit to feature branch?
- I am still not getting context why we need to commit and how does it will effect the release pipeline


I would like to have a call to a better understanding of this issue before implementing it.

**Comment by robe070** [comment]
1. the main template will be modified by Rizwan's script: aws-templates\CloudFormationWindows\lansa-master-win.cfn.template
2. It will commit to the current branch
3. The template is then uploaded to S3 for execution. 
4. This template will then be used by the following tests to ensure the changes made by Rizwan's script is successful.

I have other meetings to attend to. I hope that is sufficient.

If not, you can at least create a stage as described above and a task to commit and push that file to the current branch. I think it would be good for you to clone the pipeline and do tests there until its working. Unless you believe its trivial. I'm concerned about setting up the permissions.

**Comment by ganeshk146** [comment]
@robe070 , 
When the repo is cloned to the workspace directory It is pointing to a commit and not to any branch 

<img width="899" alt="Screenshot 2021-06-14 at 10 08 12 AM" src="https://user-images.githubusercontent.com/72592790/121839793-77df2300-ccf8-11eb-8d0d-0bff1d038560.png">

- we have to do a couple of things to fix it

1. We have to generate personal access token in the user account (right now I generated a personal access token with permissions to push/commit changes)
2. run git config commands to set origin URL with PAT(personal access token) and user email id and user name (used to display who committed the changes)
3. git add  command to add the files
4. git commit to commit the files to git
5. git push command to push the changes to git

Please see the build https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-pipeline-progress&releaseId=217

Once the task completes successfully we can see the file changes in the git repo
<img width="1397" alt="Screenshot 2021-06-14 at 10 05 50 AM" src="https://user-images.githubusercontent.com/72592790/121839616-220a7b00-ccf8-11eb-9dd6-9f1329eb2313.png">


Please let me know If any changes are required

**Comment by robe070** [comment]
Thank you for the clear comments. And good investigation and solution. Great work.

The inline script is now non-trivial, so it now needs to be in a file. And you'll need to provide project variables for the settings required in steps (1) and (2) above and refer to them in the script. Its fine to get it working inline before a final change to put the script in a file.

So I presume you need me to provide values for the settings in (1) and (2) that will work on the live repo lansa/aws-templates?
Tell me what the variable names are and create them in Image Release 2.0 as well as your own clone and I can put the values in.

**Comment by robe070** [comment]
On further thought, I think we need to discuss the best way to structure the pipeline. Considerations include:
1. The commit will need to be in the same Agent as Rizwan's task is run in so that the file change is picked up.
2. It seems sensible for Rizwan's task to add the file to git after changing it.
3. Maybe the Commit & Push should also be done from Rizwan's code?
4. Maybe the setup steps should be a separate script run at the start of the job in which Rizwan's script makes the changes? And this to be a script file so it can be run in various Jobs that require write access to the repo.
5. And Add/Commit/Push could be inline in Rizwan's script.

**Comment by ganeshk146** [comment]
@robe070 ,

As per the discussion, This task is giving write permission to the repo (configure URL, username and email)

**Comment by robe070** [comment]
The directory of the git repo must also be passed in. Then its a generic script which may be used for any git repo.

**Comment by ganeshk146** [comment]
@robe070 , 
Please review the PR: https://github.com/lansa/aws-templates/pull/19
Here is the successful release pipeline URL https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-environment-logs&releaseId=226&environmentId=3153

**Comment by ganeshk146** [comment]
@robe070 
> Tell me what the variable names are and create them in Image Release 2.0 as well as your own clone

I added variables to both pipelines and here is the screenshot.
<img width="1427" alt="Screenshot 2021-06-15 at 1 49 01 PM" src="https://user-images.githubusercontent.com/72592790/122018512-902a6d00-cde0-11eb-99ce-7341308f667a.png">
<img width="1434" alt="Screenshot 2021-06-15 at 1 48 54 PM" src="https://user-images.githubusercontent.com/72592790/122018556-99b3d500-cde0-11eb-8bc9-29006465c849.png">

**Comment by robe070** [comment]
I believe that the GitRepoName and GitLansaAwsTemplatesBranch may be derived from the _lansa_aws-templates artefact - from system variables. Please investigate. _lansa_aws-templates may be presumed static and pass that in to your script.

![image](https://user-images.githubusercontent.com/4089160/122021404-fc20cb80-ce08-11eb-9225-e04b21dbbd71.png)

And how do I generate the Url for the lansa/aws-templates repo? This instruction should be part of the description of the parameter in the script.

**Comment by ganeshk146** [comment]
@robe070 ,
> I believe that the GitRepoName and GitLansaAwsTemplatesBranch may be derived from the _lansa_aws-templates artifact - from system variables.

I checked The Release Artifacts system variables, I am not able to able to access the GitLansaAwsTemplatesBranch and GitRepoName (i.e. source alias). 
- Reason for  GitLansaAwsTemplatesBranch not able to access system variables because the variable contains "-". 
- Source alias name (GitRepoName) is not available with the system variables.


> And how do I generate the Url for the lansa/aws-templates repo? This instruction should be part of the description of the parameter in the script.

- Added comments in the script and commit-id: https://github.com/CelestialSystem/aws-templates/commit/de609a2fb0492563e99be38492817b905e6e24d8

**Comment by ganeshk146** [comment]
@robe070 ,

Please find the URL (release pipeline) and testing is successfull.
https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-environment-logs&releaseId=252&environmentId=3520

I request you to please merge the PR: https://github.com/lansa/aws-templates/pull/19
