### ISSUE TITLE
New stage Commit US template changes

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#123]
**Commit US template changes**: 
Commits the master template changes to the `aws-templates` git repo in `support/scalable` branch and pushes changes to GitHub. New job `Commit US AMI Changes` that has all the `US IMG Test*` jobs as prereqs (These changes now become the default images for all template tests in `us-east-1`).

Merge `support/scalable` branch into `support/scalable_marketplace` branch and push to GitHub

Use a Powershell script saved in the lansa/aws-templates repo in a scripts directory

**Comment by ganeshk146** [comment]
@robe070 ,

This task is about adding the git commands (git add ., git commit , git push) to Rizwan's script written for #119

**Comment by robe070** [comment]
...and merging too.

**Comment by robe070** [comment]
@anant-k-agrawal This should be assigned to Rizwan to add these behaviours when doing #121. Note that there is an extra step for #121 compared to #119 - the merge of the branches. If Rizwan has the requisite git skills then it would be most appropriate for him to do it.

**Comment by ganeshk146** [comment]
@robe070 ,

As part of this task, I have 2 branches 
1. `feature/119` (in live release pipeline it will be `support/scalable`)
2. `feature/119-clone` (in live release pipeline it will be `support/scalable_marketplace`)

- I added a task called "commit and push changes to git repo" in this [release](https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-environment-logs&releaseId=271&environmentId=3789) pipeline for testing purpose.
- I tested the pipeline and the test is successful
- You can see the commits in both branches for the file name "test.cfn.template".

<img width="1380" alt="feature:119-changes" src="https://user-images.githubusercontent.com/72592790/122506785-9f95fa00-d01c-11eb-8a70-e1e855ec6a74.png">
<img width="1333" alt="feature:119-clone-changes" src="https://user-images.githubusercontent.com/72592790/122506806-a7ee3500-d01c-11eb-8495-06b867c736dc.png">

**Comment by ganeshk146** [comment]
@robe070 ,

Sorry , I clicked the Close Issue button by mistakenly

**Comment by robe070** [comment]
All git commands need to have the return code tested. If its an error, display the error code, and an appropriate message relevant for the git command and then throw.

**Comment by ganeshk146** [comment]
@robe070 ,

I added the exit codes for all git commands, Please find the successfull build
https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-pipeline-progress&releaseId=387

If there is any conflicts it will fail with exit 1
https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-environment-logs&releaseId=377&environmentId=5679

**Comment by robe070** [comment]
1. Looks like the error messages are not being displayed
2. I think for at least the Delete temp branch step, its duplicated code. That MUST be put in a script file.

**Comment by ganeshk146** [comment]
@robe070 ,

I made the changes and tested with pipeline 
When Git failure occurs https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?releaseId=399&_a=release-pipeline-progress

When Git commands success https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-pipeline-progress&releaseId=397

**Comment by robe070** [comment]
I can't see a failure with this:
When Git failure occurs https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?releaseId=399&_a=release-pipeline-progress

**Comment by ganeshk146** [comment]
@robe070 ,
The failure is in the last stage "Commit US template changes" https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?releaseId=399&_a=release-pipeline-progress
`git pull origin  test_pipeline_rizwan_sharmil --allow-unrelated-histories failed`
<img width="1055" alt="Screenshot 2021-06-29 at 1 29 16 PM" src="https://user-images.githubusercontent.com/72592790/123760103-292bae80-d8de-11eb-9ca6-940572421dfd.png">

**Comment by robe070** [comment]
Looks good.
