### ISSUE TITLE
New Stage Marketplace

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#124]
**Marketplace**: 
Manual step. Submit US AMIs to AWS MP.
Manually update a copy of the Product Load Form (today's date in the name) with the US AMIs.

**Comment by ganeshk146** [comment]
@robe070 ,

This stage is added into image release pipeline 2.0 and here is the URL for successful build
https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-pipeline-progress&releaseId=360
