### ISSUE TITLE
Change Task AWS Template CD S3 patch/paas to use repo version of templates

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#125]
**S3 patch/paas**
Currently this task is uploading the CI artifact.

Upload the support/scalable branch to S3 patch/paas sub folder. (This version of the templates is using the git branch template parameter to locate the nested templates.)

**Comment by ganeshk146** [comment]
@robe070 ,

I added my changes to template Release 2.0 pipeline and here is successfull run of the build https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-pipeline-progress&releaseId=411

**Comment by ganeshk146** [comment]
@robe070 ,

Please review this PR and request to merge https://github.com/robe070/cookbooks/pull/153
