### ISSUE TITLE
Change task AWS Template CD S3 support/scalable to use repo version of templates

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#126]
**S3 support/scalable**: 
Use `support/scalable_marketplace` resource to upload this branch's template to S3 support/scalable.  **(Note that the current Template URL for nested templates uses the support/scalable/marketplace folder so that needs to be changed. See Issue #126 )**

**Comment by ganeshk146** [comment]
Hi @robe070 ,

Please find the successful unit test done https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-environment-logs&releaseId=429&environmentId=6592
