### ISSUE TITLE
New Stage AWS Template CD Merge to Marketplace

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#128]
**Merge to Marketplace**
Merge `support/scalable` into `support/scalable_marketplace`.

Refer to [Wiki ](https://github.com/robe070/cookbooks/wiki/AWS-Release-Pipelines-High-Level-View) for merge possibilities.

**Comment by ganeshk146** [comment]
@robe070 ,

As discussed in the call I am going to do below changes
- Move https://github.com/CelestialSystem/aws-templates/blob/feature/119/scripts/GitRepoWriteAccess.ps1 to cookbooks repo
- Add cookbooks Artifacts into Image Release 2.0 
- Change the path uses GitRepoWriteAccess.ps1 in Image Release 2.0 pipeline
- Run the GitRepoWriteAccess.ps1 from aws-template to cookbooks repo
- Move the Merge Stage inline script in Template pipeline 2.0 into the cookbooks repo script and use it Template pipeline 2.0
- Remove disabled step -> `Test Image Version` from Image Release 2.0 pipeline

**Comment by robe070** [comment]
Also please change the Agent being used to windows 2019 on all Jobs. e.g.
![image](https://user-images.githubusercontent.com/4089160/124085589-8ddc3a00-da93-11eb-93b3-c4c740183383.png)

**Comment by ganeshk146** [comment]
@robe070 ,
The above change needs to be done for Image Release pipeline 2.0 and Template Pipeline 2.0 , Am I correct?

**Comment by robe070** [comment]
Correct

**Comment by ganeshk146** [comment]
@robe070 ,

Please find the successful test URL https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-pipeline-progress&releaseId=429

**Comment by ganeshk146** [comment]
PR for 128 ticket Please review it and requesting to merge https://github.com/robe070/cookbooks/pull/155
