### ISSUE TITLE
Change Stage AWS Template CD - Shoe Size & VPC Tests

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#129]
**Shoe Size & VPC Tests**: 
Test all the variants of the templates using the templates in S3 patch/paas

Ensure that Issue #115 changes have been made and change the url to the S3 patch/paas folder

Create new stages so that all tests are in their own Stage. 1 job per stage creating 1 CF stack and testing it

**Comment by sharirpcs** [comment]
Testing is completed and successful.Please review it https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_release?definitionId=6&view=mine&_a=releases

**Comment by robe070** [comment]
Please provide release url, not pipeline url.

**Comment by sharirpcs** [comment]
Release-71 has got changes tested.Please review it.
https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_release?view=all&_a=releases&definitionId=6
