### ISSUE TITLE
New stage AWS Template CD - Validate Template URL

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#130]
**Validate Template URL**: 
Test the Small Size template only using the templates in S3 support/scalable. This validates that the template URLs are correct for publication. Must create a New VPC so that the TemplateUrl parameter is fully tested.

**Comment by robe070** [comment]
Note that the VPC parameters must be set for a **New VPC**. Currently its using an existing VPC.

**Comment by sharirpcs** [comment]
Release-88 has got the changes tested.Please review it.Here is the URL
https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_release?view=all&_a=releases&definitionId=6
