### ISSUE TITLE
AWS CD pipelines - Refactor all Powershell inline scripts into script files 

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#131]
**Refactor all Powershell inline scripts into script files**
In the AWS CD pipelines only. 
Must be done early in the PRD before Issues which are required to create new tests.

For example:
1. Set Gate Variable
2. Delete previous Failed stack
2. URL Tests
3. Test Image Version
etc

Please review each Inline script and replace with a script file if it is non-trivial. Any Inline scripts you decide are trivial, please inform the Architect ASAP.

As you complete each Script File, create a PR (only one required for this entire Issue. Just keep pushing more changes to the same PR)

Note that these Powershell scripts may be left as inline:
2. Output Gate Variable
...and there may be more

And ALL new powershell must NOT be INLINE. Note that for development inline scripts may be used, because that is usually much quicker, but once its unit tested it MUST be immediately converted to a script file. New scripts will be those required to commit and merge changes in the GitHub repos.

Scripts to be stored in the aws-templates repo scripts folder.

**Comment by ganeshk146** [comment]
@robe070 ,

As we discussed on our last call the proposed solution was

1. https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_release?view=all&_a=releases&definitionId=5 (Image Release 2.0)

2. https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_release?view=all&_a=releases&definitionId=6 (Template Release 2.0)

In the above releases, we need to move the inline script to the aws-templates repo scripts folder.

We are in the process of updating it, We will update the changes soon.

**Comment by robe070** [comment]
Those are links to the pipelines. If you've actually changed a specific Pipeline Task, then name it please. You haven't changed the first 3 tasks in either of the pipelines. And there are no pipeline runs showing you've tested it.

**Comment by robe070** [comment]
@ganeshk146 I've made a comment against PR 17:
https://github.com/lansa/aws-templates/pull/17

**Comment by robe070** [comment]
I've just realised that you have only made these changes for the Image Release pipeline. The Template Release pipeline also needs inline scripts refactored.

And other Issues may continue as they are all related to the Image Release pipeline.

You may address this anytime before you start making any other changes to the Template Release pipeline. And its probably better done sooner rather than later so the knowledge gained in the Image Release has not had time to fade.

Also note that I'm almost certain that most of the scripts required are also in the Image Release pipeline, so re-use them.
@anant-k-agrawal @div1127

**Comment by robe070** [comment]
Also `DeletePreviousFailedStack.ps1` Is still referring to `$(Gate.stack)`. A parameter is passed in from the pipeline, but there is no parameter on the script.

**Comment by anant-k-agrawal** [comment]
This requirement is not evident by reading the ticket description. No worries @robe070, as you suggested, let's finish it in the first place.

**Comment by robe070** [comment]
Its not spelt out, and its implied by this phrase "In the AWS CD pipelines only." I did also verbally state at the beginning that it was both of the CD pipelines.
