### ISSUE TITLE
AWS Template CD - Marketplace URL Tests

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#132]
**Marketplace URL Tests**: 
AKA "preview Tests".

Use the URL provided by AWS Marketplace to execute 1 test in each of the regions listed below using a different image and different shoe size for each test.

Once the listing has been accepted by AWS Marketplace and its now in preview the focus shifts to validating the changes made to the templates by AWS Marketplace. AWS make 2 changes. The first is to change the AMI Ids in every supported region for every image version we publish. The second is to validate that the TemplateUrl parameter has been changed correctly. 

The [Wiki](https://github.com/robe070/cookbooks/wiki/AWS-Release-Pipelines-High-Level-View) describes how to input the TemplareUrl to the pipeline. So firstly use a Manual Intervention agentless task to display the name of the file that must be updated with the TemplateUrl. Then use another task to read the S3 file that contains the TemplateUrl and set the task variable.
Pipeline Variable,  : `s3://lansa/templates/support/scalable/marketplace/TemplateUrl.txt`
Output Variable Reference Name: `Task`
Task Variable property: `Task.TemplateUrl`

Firstly the images are tested to ensure they are accessible. The first time the images were published many AMIs were not correctly copied. This is a quick test to ensure thats all OK. There is a script called `TestTemplateMappingAMI.ps1`. This takes a TemplareUrl parameter being the Url supplied by AWS Marketplace - `Task.TemplateUrl`. The script throws a fatal error if a test fails.

Given the algorithmic nature of the changes made by AWS Marketplace for the AMI Ids, it seems reasonable to limit the template tests so that each Image version (6 of) is used once in a test, that each shoe size is used just once in a test, and that each of those tests is performed in a different region. Once for Preview and once when Live. Thus there are 12 tests in total. The regions chosen are presumed to be the most important for LANSA customers: 

For Preview: US East (N. Virginia), US West (N. California), US West (Oregon), Asia Pacific (Tokyo), Europe (London) and Europe (Paris). 

This requires data entry on the fly. See *Inputting a Template URL* in the [Wiki](https://github.com/robe070/cookbooks/wiki/AWS-Release-Pipelines-High-Level-View)

Each Test is to follow the standard structure (**Its a requirement that the Architect signs off on the first test before further tests are cloned from it**) :
![image](https://user-images.githubusercontent.com/4089160/110423437-23bf1400-80f5-11eb-99ce-33689b7202fa.png)

**Comment by robe070** [comment]
These are the parameters required when creating all the stacks, including `us-east-1`, though note that its variable names end with `US` not `-us-east-1`. 

And these REPLACE the parameters of the same name, and the parameter DBSubnetGroupName must be removed.

It would save a lot of typing if the [region] was available as a shell variable. Then this only needs to be setup once and then cloned. Please investigate this possibility.

```JSON
{
    "ParameterKey": "CreateVPC",   
    "ParameterValue": "Yes"
}, {
    "ParameterKey": "CurrentVPC",   
    "ParameterValue": "$(CurrentVPC-[region])"
}, {
    "ParameterKey": "AvailabilityZones",   
    "ParameterValue": "$(AvailabilityZones-[region])"
}, {
    "ParameterKey": "NumberOfAZs",   
    "ParameterValue": "$(NumberOfAZs-[region])"
}, {
    "ParameterKey": "ELBSubnetIds",   
    "ParameterValue": "$(ELBSubnetIds-[region])"
}
```

**Comment by ganeshk146** [comment]
@robe070 , 

Here is what I am thinking, I will be creating the template parameter JSON using PowerShell script before Deploy Stackstep. 
- create a file called TemplateParameter-us-east-1.json for us-east-1 region
- and this file contents will be TemplateParameter-us-east-1.json

```
{
    "ParameterKey": "CreateVPC",   
    "ParameterValue": "Yes"
}, {
    "ParameterKey": "CurrentVPC",   
    "ParameterValue": "$(CurrentVPCUS)"
}, {
    "ParameterKey": "AvailabilityZones",   
    "ParameterValue": "$(AvailabilityZonesUS)"
}, {
    "ParameterKey": "NumberOfAZs",   
    "ParameterValue": "$(NumberOfAZsUS)"
}, {
    "ParameterKey": "ELBSubnetIds",   
    "ParameterValue": "$(ELBSubnetIdsUS)"
}

```
- likewise I will create different types of JSON files depends on the region input and reference it in stack creation by using the local file option avaiable.
- Please let me know your thoughts.

**Comment by ganeshk146** [comment]
The changes are done , For testing We need a real market place URL
