### ISSUE TITLE
AWS Template CD - Run Live Tests

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#133]
**Run Live Tests**: 
AKA "Production Tests".

Use the URL provided by AWS Marketplace to execute 1 test in each of the regions listed below using a different image and different shoe size for each test.

N.B. These tests are identical to the tests created for Issue #132, except that different Regions are used. So those stages should be cloned. It makes this Issue very easy to complete.

Once the listing has been accepted by AWS Marketplace and its now in preview the focus shifts to validating the changes made to the templates by AWS Marketplace. AWS make 2 changes. The first is to change the AMI Ids in every supported region for every image version we publish. The second is to validate that the TemplateUrl parameter has been changed correctly. Given the algorithmic nature of the changes made by AWS Marketplace for the AMI Ids, it seems reasonable to limit the tests so that each Image version (6 of) is used once in a test, that each shoe size is used just once in a test, and that each of those tests is performed in a different region. Once for Preview and once when Live. Thus there are 12 tests in total. The regions chosen are presumed to be the most important for LANSA customers: 

For Live: US East (Ohio), Asia Pacific (Sydney), Canada (Central), Europe (Frankfurt), Europe (Ireland) and Europe (Stockholm).

This requires data entry on the fly. See *Inputting a Template URL* in the [Wiki](https://github.com/robe070/cookbooks/wiki/AWS-Release-Pipelines-High-Level-View)

Each Test is to follow the standard structure (**Its a requirement that the Architect signs off on the first test before further tests are cloned from it**):
![image](https://user-images.githubusercontent.com/4089160/110423437-23bf1400-80f5-11eb-99ce-33689b7202fa.png)

**Comment by ganeshk146** [comment]
The changes are done , For testing We need a real market place URL
