### ISSUE TITLE
Implement AWS JPN images CI pipelines

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#137]
This issue requires Issue #136 to be complete
This issue requires Project `P1 AWS Images CD` to be complete.

Add JPN Image jobs to `AWS Images - Cookbooks CI` pipeline by duplicating the 4 existing Win2016 and Win2019 ENG image builds and making them produce JPN images.

Parameters to scripts/bake-scalable-azure-image-pipeline.ps1 will be changed as follows from the equivalent English versions:

OS | VersionMajor | VersionMinor | AmazonAMIName | Language | VersionText
-- | -- | -- | -- | -- | --
Windows 2016 | 14 | 2 | Windows_Server-2016-Japanese-Full-Base* | JPN | w16d-14-2j
Windows 2016 | 15 | 0 | Windows_Server-2016-Japanese-Full-Base* | JPN | w16d-15-0j
Windows 2019 | 14 | 2 | Windows_Server-2019-Japanese-Full-Base* | JPN | w19d-14-2j
Windows 2019 | 15 | 0 | Windows_Server-2019-Japanese-Full-Base* | JPN | w19d-15-0j

Add JPN specific tests as described in #136.

Once that is working correctly, add the same jobs to `Build Image Release Artefacts` pipeline, with differences that match the differences between the existing jobs in the two pipelines, like image names.

**Comment by ganeshk146** [comment]
AWS Images - Cookbooks CI testing URL: https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_build/results?buildId=1098&view=logs&j=33c90b4a-9a8c-5ab6-4a2d-e789e8f2ea10

Build Image Release Artefacts testing URL: 
https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_build/results?buildId=1089&view=results

**Comment by ganeshk146** [comment]
@robe070 ,

I updated the parameter name and ran tests and the build is successfull. Please review the PR https://github.com/robe070/cookbooks/pull/162
