### ISSUE TITLE
Implement Japanese AWS Images CD Pipeline

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#138]
Requires project `P1 AWS Images CD` to be completed

In a similar manner to the English pipeline, add stages and jobs for Japanese.
This predominantly involves duplicating the English Stages and Jobs and providing different image ids, language identifiers and different test cases.

Set DBCCSID=Japanese_CI_AS

The MSI to use for the test case is https://lansa.s3-ap-southeast-2.amazonaws.com/app/Test/JPTEST_v1.0.0_ja-jp.msi
The tests to run are:
1. [url root]/cgi-bin/probe
2. [url root]/cgi-bin/lansaweb?about
3. [url root]/JPNTESTs/TEST 
4. [url root]/JPNTESTs/DUMMY
Each test fails if it does not return html error code of 200.

When duplicating Stages from the English, split stages with multiple jobs into 1 job per stage.

**Comment by ganeshk146** [comment]
Image 2.0 Pipeline testing for JPN images
https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?releaseId=599&_a=release-pipeline-progress


Template 2.0 pipeline testing for JPN images
https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-pipeline-progress&releaseId=598

**Comment by robe070** [comment]
Please name the AUS template deployment stages along the same lines as suggested for Azure in slack yesterday. Namely 

[Region Abbreviation] [some name] [Image version]"

e.g. `AUS Small Shoe Size w12r2-14-2`

The Marketplace URL Tests that have the `Wait for Live stage` as prerequisites need a name change. Instead of the text `Marketplace URL Tests` it needs to be changed to `Prod`, for Production

**Comment by robe070** [comment]
...and remove the dashes `-`, it takes up precious space.

And the remaining `Marketplace URL Tests` to have that text replaced with `Preview`

**Comment by robe070** [comment]
And Canada central is tested twice. Please change one and name the stage remaining that is using Canada Central as `Canada Central`

**Comment by ganeshk146** [comment]
The requested changes are done https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseDefinition?definitionId=6&_a=definition-pipeline

**Comment by ganeshk146** [comment]
Hi @robe070 ,

In preview stage tests we are using "London" and "Oregon" 2 times.
In production stage tests we are using "Frankfurt" and "Canada Central" 2 times

Please provide me the VPC parameters for new regions to be added.

**Comment by robe070** [comment]
@sharirpcs produced the VPC parameters previously. So please work with him to obtain them. Could wait for him to complete #103 or he could direct you as to what you need to do.

Regions to use are:
Mumbai ap-south-1
Hong Kong ap-east-1
Milan eu-south-1
Bahrain me-south-1

And change Canada Central to just Canada.

**Comment by sharirpcs** [comment]
I have showed @ganeshk146 how to obtain the VPC parameters for Mumbai ap-south-1 region and he will follow the same for rest of the regions

**Comment by ganeshk146** [comment]
> @sharirpcs produced the VPC parameters previously. So please work with him to obtain them. Could wait for him to complete #103 or he could direct you as to what you need to do.
> 
> Regions to use are:
> Mumbai ap-south-1
> Hong Kong ap-east-1
> Milan eu-south-1
> Bahrain me-south-1
> 
> And change Canada Central to just Canada.

added the changes as per comments
https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseDefinition?definitionId=6&_a=definition-pipeline

**Comment by anant-k-agrawal** [comment]
@ganeshk146: Is there anything remaining from your side on this ticket?

**Comment by ganeshk146** [comment]
@anant-k-agrawal ,

I don't think anything is left out.

**Comment by ganeshk146** [comment]
@robe070 ,

Please let me know any changes is required from my side

**Comment by robe070** [comment]
The pipeline needs to be taken through the publishing process before it can be closed.

**Comment by robe070** [comment]
This needs to be done very carefully.

In the AWS template parameter field,  the ParameterKey below is specified twice - once for each of the below values. This is confusing when you come to check the parameters because its the last value that takes effect.

"11WebserverOSVersion" = $(WebserverOSVersionKey)

So, the entire pipeline has been run or is running now, so the last value is the one being used. In the example below the Value used in "win2016". So the change must ensure thats the value used. And at the same time, we do not want a literal value for "win2016". So create a variable in the Template Parameters group which is called WebserverOSPreviousVersionValue with the value "win2016".
```
,{
    "ParameterKey": "$(WebserverOSVersionKey)",
    "ParameterValue": "$(WebserverOSVersionValue)",
},
```
```
, {
    "ParameterKey": "11WebserverOSVersion",   
    "ParameterValue": "win2016"
}
```

So the correct code for the above example is:
```
, {
    "ParameterKey": "11WebserverOSVersion",   
    "ParameterValue": "$(WebserverOSPreviousVersionValue "
}
```

**Comment by robe070** [comment]
Also the Frankfurt Production Stage is using and testing the English Image. It is meant to be the Japanese image

**Comment by ganeshk146** [comment]
@robe070 ,
The above changes in both the pipelines are done, Please review them.
cc: @anant-k-agrawal , @div1127

**Comment by robe070** [comment]
The name of the variable needs to be `WebserverOSPreviousVersionValue`  not `WebserverOS2016VersionValue`

Frankfurt Prod Stage needs Collation set to JPN and the URL tests need to specify Japanese. See other JPN tests for details.

**Comment by ganeshk146** [comment]
for 2019 what should be the variable?

**Comment by robe070** [comment]
> for 2019 what should be the variable?

It already exists `WebserverOSVersionValue`

**Comment by ganeshk146** [comment]
> > for 2019 what should be the variable?
> 
> It already exists `WebserverOSVersionValue`

It was added by me when I was fixing the comments, Just to confirm

**Comment by robe070** [comment]
It existed this morning. I would have preferred it to be of the same structure as JPN. Namely `WebserverOSLatestVersionValue`

**Comment by ganeshk146** [comment]
Now Both Image and Template pipelines are updated to use variables like
win2012 -> WebserverOSVersionValue
win2016 -> WebserverOSPreviousVersionValue
win2019 -> WebserverOSLatestVersionValue

**Comment by robe070** [comment]
Thats is excellent. Thank you

**Comment by ganeshk146** [comment]
@robe070 ,

All comments are fixed, Is that ok to close this ticket?
cc: @div1127, @anant-k-agrawal

**Comment by robe070** [comment]
all comments are coded. They are not tested. Testing is waiting for Template publication as I said in Slack. Want to use our limited quota on the main game.

**Comment by ganeshk146** [comment]
Is that ok to run entrie pipeline in AWS side (both Template and Image release pipeline) or only production stages is enough?

**Comment by robe070** [comment]
No its not OK to run any pipelines. I want the resources available for the Azure Template pipeline.

**Comment by robe070** [comment]
AWS Image Pipeline
Only win2012 images are missing are missing from build 1155. All other stages should not be skipped.

Stage w16d-15-0 US IMG Test is skipped and shouldn't be. Gate variable must be wrong and thus maybe stack and test parameters are wrong too.

Stage w16d-14-2j US IMG Test, ditto

I've set these Stages running. Please check that they succeed and are not skipped. So must look at the logs. Take screen capture of the 4 logs and post them here.

And don't worry about Delete Stack failures. AFAIC thats a pass. Nice to have all ticks and not necessary.

**Comment by ganeshk146** [comment]
The stages skipped because the "Artifacts are not found" As per this task "Overwrite ap-southeast-2 AMI Ids with us-east-1 AMI Ids" only 4 AMI-ids exists, Please see the below image and I checked the Gate Variable setting it is setting properly.
I changed only "Deploy Aws Template" step parameters and still that step is not executed 
<img width="1089" alt="Screenshot 2021-10-01 at 5 48 20 AM" src="https://user-images.githubusercontent.com/72592790/135547261-3399b762-9f6f-4624-be05-f32c743bd80a.png">

**Comment by ganeshk146** [comment]
<img width="1194" alt="Screenshot 2021-10-01 at 5 53 31 AM" src="https://user-images.githubusercontent.com/72592790/135547562-54ac0226-0b9d-4e38-a42a-0c1c36cecc21.png">
<img width="1182" alt="Screenshot 2021-10-01 at 5 53 14 AM" src="https://user-images.githubusercontent.com/72592790/135547569-d54ea8d9-ce9b-4fda-a371-cfd8c53d18ac.png">
<img width="1172" alt="Screenshot 2021-10-01 at 5 53 00 AM" src="https://user-images.githubusercontent.com/72592790/135547571-062b0954-2cde-4f92-9c18-b216b9919d91.png">
<img width="1176" alt="Screenshot 2021-10-01 at 5 52 42 AM" src="https://user-images.githubusercontent.com/72592790/135547574-4adbe66c-1fe5-46d9-a974-b8528f9a027a.png">

**Comment by robe070** [comment]
I forgot to paste in the list of stages to check. The ones that are active here:
![2021-10-01_07-36-02](https://user-images.githubusercontent.com/4089160/135548071-8602f1d9-d039-4f60-832c-37852c190407.png)

The skipping then is because the AMIs do not exist in S3. The copies need to be done. I'll do this.

**Comment by robe070** [comment]
I have fixed up S3.

I've started the wrong tests! The AUS ones! No matter. I've ALSO started the US tests. When they are complete, please check all the US logs and paste them into here.

**Comment by robe070** [comment]
And about the efficacy of the prior tests, the live tests confirm that every image published is the correct image.

**Comment by ganeshk146** [comment]
@robe070 ,
<img width="1164" alt="Screenshot 2021-10-01 at 8 46 06 AM" src="https://user-images.githubusercontent.com/72592790/135559988-a3aac0d5-ee11-47a5-98e5-1d84f09b20fe.png">
<img width="1186" alt="Screenshot 2021-10-01 at 8 45 59 AM" src="https://user-images.githubusercontent.com/72592790/135560002-13d4a752-16e9-4244-a3a4-48ee84ca5fb0.png">
<img width="1173" alt="Screenshot 2021-10-01 at 8 45 51 AM" src="https://user-images.githubusercontent.com/72592790/135560006-635c6f21-0bb8-40e5-9743-9f384e28b8f5.png">
<img width="1165" alt="Screenshot 2021-10-01 at 8 45 43 AM" src="https://user-images.githubusercontent.com/72592790/135560010-a0df8392-633c-4ab2-b977-98944f0df34a.png">
<img width="1174" alt="Screenshot 2021-10-01 at 8 45 36 AM" src="https://user-images.githubusercontent.com/72592790/135560014-0984fb7c-1be7-474c-b7c7-f6e63b602852.png">
<img width="1163" alt="Screenshot 2021-10-01 at 8 45 28 AM" src="https://user-images.githubusercontent.com/72592790/135560018-45a7762b-7af4-48cd-b3fa-518e81b9507a.png">
<img width="1165" alt="Screenshot 2021-10-01 at 8 45 20 AM" src="https://user-images.githubusercontent.com/72592790/135560025-e8ae8fd3-19c8-45e7-8ad7-9d41d535726d.png">
<img width="1196" alt="Screenshot 2021-10-01 at 8 45 05 AM" src="https://user-images.githubusercontent.com/72592790/135560030-210d6ae0-1599-47bb-8647-7511feafd6c0.png">

**Comment by robe070** [comment]
@ganeshk146 
https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?releaseId=649&_a=release-environment-logs&environmentId=11238
When you made the changes to change the WebOSVersion you completely removed the parameter for the 2 stages which have failed in this release. Please correct by using the correct JPN Windows Version

**Comment by ganeshk146** [comment]
@robe070 ,
I am working on fixing the parameters issue got removed mistakenly.

**Comment by ganeshk146** [comment]
> https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?releaseId=649&_a=release-environment-logs&environmentId=11238

This errors are fixed in 2 stages i.e.
1. "Milan Prod w16d-14-2j"
2. "Bahrain Prod w19d-15-0j"

**Comment by robe070** [comment]
I've created a new releases and deployed the 2 stages you've changed
