### ISSUE TITLE
Implement Azure JPN images CI pipelines

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#140]
This issue requires Issue #136 to be complete
This issue requires Project `P2 Azure` to be complete.
This issue requires Project `P4 AWS Japanese Images` to be complete.

Add JPN Image jobs to `Azure Images - Cookbooks CI` pipeline by duplicating the existing 4 ENG Win2016/2019 image builds and making them produce JPN images.

Once that is working correctly, add the same jobs to Azure `Build Image Release Artefacts` pipeline.

**Comment by Arshpreet1002** [comment]
Added JPN Image jobs to Azure Images - Cookbooks CI and Azure Build Image Release Artefacts pipeline by duplicating the existing 4 ENG Win2016/2019 image builds and making them produce JPN images.

Testing is also Done.
https://dev.azure.com/VisualLansa/Lansa%20Azure%20Scalable%20License%20Images/_build/results?buildId=1106&view=results
https://dev.azure.com/VisualLansa/Lansa%20Azure%20Scalable%20License%20Images/_build/results?buildId=1111&view=results

**Comment by robe070** [comment]
Waiting for PR to be cleaned up and the JPN images available for testing.

**Comment by robe070** [comment]
JPN Images now available. It is now urgent this is completed. Your git changes are required to be merged with JPN image changes. Are you not working today?

**Comment by Arshpreet1002** [comment]
Hi Rob,Please close the Ticket.
