### ISSUE TITLE
AWS Image Release CD pipeline jobs fail if an artifact has not been built

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#149]
The pipeline was designed to not fail if an artifact has not been built. Its just that there is a test missing.

SetGateVariable.ps1 sets the $(Gate.IsEnabled) flag appropriately. **ALL** The following tasks require a condition to be added to test this variable. You can look at the Azure Image Release CD pipeline for an example as shown below:

![image](https://user-images.githubusercontent.com/4089160/120573235-958ecb80-c460-11eb-84be-830eabf9c4de.png)

**Comment by ganeshk146** [comment]
@robe070 , Added the custom condition for https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseDefinition?definitionId=5&_a=definition-tasks&environmentId=64 job tasks

**Comment by robe070** [comment]
You will need to apply the changes to 1 of the other jobs in order to test with artefact 873 that your changes are working correctly. When you create the release, change the Job IMG Test w12r2d-14-2 to manual. When thats successful, apply to all t

When its successful, please  point out to me which release of the pipeline demonstrates the successful implementation of this code.

**Comment by ganeshk146** [comment]
@robe070 , After doing this step "change the Job IMG Test w12r2d-14-2 to manual" I ran the release pipeline it is successful
https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-environment-logs&releaseId=174&environmentId=2600.

I applied the same change to other jobs as well.
https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseDefinition?definitionId=5&_a=environments-editor-preview

**Comment by robe070** [comment]
Release 53 is not successful. The idea of `setting  Job IMG Test w12r2d-14-2 to manual` was to be able to immediately get to see the other jobs failing. Which they still are. They MUST NOT FAIL! The code is not correct. The whole point of the code is to skip the jobs for which there is no artifact. And that is not occurring. 873 only has an artifact for `w12r2d-14-2`. Thats why you must focus on that run before propagating your change to  other Jobs. 

This is the main part of my request above `You will need to apply the changes to 1 of the other jobs in order to test with artefact 873 that your changes are working correctly.` So, pick another job, say `IMG Test w12r2d-15-0` and ensure that is flagged as successful with Run 873 - because all the tasks are skipped.

**Comment by ganeshk146** [comment]
The testing is done https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?releaseId=177&_a=release-pipeline-progress
