### ISSUE TITLE
Image CI Pipeline does not pull the PR into the VM to build the image

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#156]
The defect is noticeable when the changes in the PR must be in the VM in order for the image to be built correctly. E.g. a new script is created is the most obvious - the script isn't found.

The cause is that a PR must be handled differently from a simple branch in order to pull the changes into the VM:

This post describes the solution required:

-----------------------------------------------------
To fetch a remote PR into your local repo:
```
git fetch origin pull/$ID/head:$BRANCHNAME
```
where $ID is the pull request id and $BRANCHNAME is the name of the new branch that you want to create. Once you have created the branch, then simply
```
git checkout $BRANCHNAME
```
See the official [GitHub documentation](https://help.github.com/en/articles/checking-out-pull-requests-locally) for more information.
-----------------------------------------------------

installGit.ps1 needs to be changed to detect a 'branch name' of the form `refs/pull/154/merge`. 
$BRANCHNAME = 'pr_branch`
Extract the PR number (e.g. 154).
Do the fetch and checkout as above 

This code will be required in this region of the current code:
```
    # Check out a potentially different branch
    Write-Host "Branch: $Branch"
    cmd /c git checkout -f $Branch  '2>&1' | Out-Default | Write-Host
    if ($LASTEXITCODE -ne 0 -and $LASTEXITCODE -ne 128) 
    {
        cmd /c exit $LastExitCode;
        throw 'Git checkout failed'
    }
```

The Build Image task in the Image CI Pipelines needs to have the `GitBranch` parameter set to `Build.SourceBranch` like this:
![image](https://user-images.githubusercontent.com/4089160/124734911-e78fa900-df58-11eb-9dd5-bd2a423e01fa.png)

**Comment by ganeshk146** [comment]
@robe070 ,
Please close this ticket
