### ISSUE TITLE
Azure Template: Provide Dev & Test options in template

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#17]
Add options to script for Application Gateway and when creating a new database to use settings appropriate for Development. For example, the Application Gateway would be small and 1 instance. The database would be General Purpose, Serverless, with 1.5 <= vCpus <= 12 with Gen5 hardware.

Simlarly for Test.

**Comment by robe070** [comment]
See Issue #18 for details

**Comment by ashutosh-kumar1** [comment]
@robe070, Adding the createUiDefinition file with serverless database example for your feedback:
[createUIDef file.txt](https://github.com/robe070/cookbooks/files/5620412/createUIDef.file.txt)

**Comment by robe070** [comment]
@ashutosh-kumar1 
In UI definition:

- Change `Capacity` to `Max vCores`
- Change `Min Capacity` to `Min vCores`

`Min vCores` needs to be a dropdown like `Max vCores`, but different values as per issue #18 

`Min vCores` <= `Max vCores`

`Max vCores` hint:
The maximum number of cores available to use in the database. [Learn more about costing serverless compute](https://docs.microsoft.com/en-us/azure/azure-sql/database/serverless-tier-overview). [Learn more about how Gen5 serverless parameters effect the resources available to the database server](https://docs.microsoft.com/en-us/azure/azure-sql/database/resource-limits-vcore-single-databases)

`Min vCores` hint:
The minimum number of cores to use in the database. These cores will be the minimum charge except when the database server is paused.  [Learn more about costing serverless compute](https://docs.microsoft.com/en-us/azure/azure-sql/database/serverless-tier-overview). It must be less than or equal to Max vCores. Its minimum varies according to the Max vCores selected  [Learn more about the min-max vCore relationship](https://docs.microsoft.com/en-us/azure/azure-sql/database/resource-limits-vcore-single-databases).

Add `Auto Pause Delay` parameter
Default: 60
Hint: Number of minutes to wait until pausing the database. Minimum 60. Maximum 10,080 ( 7  days)  [Learn more about costing serverless compute](https://docs.microsoft.com/en-us/azure/azure-sql/database/serverless-tier-overview).

I've emailed the hints to you in markup.

**Comment by ashutosh-kumar1** [comment]
Hi Rob, thanks for the inputs. I have incorporated the changes in the createUiDefinition file as per your comments.

- Also, I did put some extra effort to convert the 'Min vCores' fields into dropdown and have exactly the set of values that is possible to be mapped to those as per the selected 'Max vCores' value. In this way, it is more user friendly and negates the possibility for a user to select a wrong input even without accessing the link in the tooltip. The default value of 'Min vCore' selection will change as the 'Max vCore' is changed.

- For the Auto Pause Delay field, I have added a check which validates the value entered in the range of 60 - 10080. The value of this field can also be -1 as per the doc (when we want to disable it).

Please have a look at the template and provide your feedback. 
[createUiDef updated.txt](https://github.com/robe070/cookbooks/files/5624037/createUiDef.updated.txt)

**Comment by robe070** [comment]
Thank you for going the extra mile and validating the Min vCore! Looks good.

I've emailed you some minor hint changes. The rest looks good.

**Comment by ashutosh-kumar1** [comment]
Hi @robe070, The changes are incorporated and PR is raised for the same.
Please review and merge: https://github.com/lansa/azure-quickstart-templates/pull/24

**Comment by robe070** [comment]
Code complete only
