### ISSUE TITLE
Azure Template: Package up settings into 'Shoe Sizes'

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#18]
Gather some of the performance related settings into a single option so that its a simple choice of, say, a small, medium or large stack.

Needs specifics to be designed.
Example settings are:
Application Gateway
Database
Instance counts

Combine with #17

**Comment by robe070** [comment]
Overview
The starting point is that the Basics blade will have these parameters, as are currently presented:


Then there is a single drop down parameter:
Stack Size which has the values Development, Test, Small, Medium, Large and Custom. All other parameters on all other blades are hidden except for the entire Security blade and the Database Login and Password on the Database Blade. Highly preferable that the Application Gateway blade and the Installation Options blade are both not shown - an empty blade is not a good solution.

The default is Development, and choosing the Stack Size sets all the parameter defaults as specified in the following table. When switching to Custom size, the previously selected Stack Size parameter defaults will remain set as they were and are now visible for further refinement. ‘Custom’ being the view of the parameters available in the currently published template. The intention is that these Shoe Sizes are quite arbitrary and are likely to require modification and so rather than choose a few parameters to include to expose for a Shoe Size, instead only mandatory parameters are exposed and any modifications require switching to Custom, after selecting a Shoe Size thats a close fit :)

All Installation Options blade parameters use the default values.

Parameter values will be left as the default except for the following parameters:
Note that a parameter must have a value specified for every Shoe Size when 1 or more Shoe Sizes requires a non-default value.


Parameter | Development | Test | Small | Medium | Large
-- | -- | -- | -- | -- | --
App VM Size | B4MS | B4MS | B4MS | B12MS | B20MS
Maximum Instance Count | 100 | 100 | 100 | 100 | 300
Web Server Max Connect | 20 | 20 | 20 | 60 | 90
AG SKU Tier | Standard | Standard | Standard | Standard_V2 | WAF_V2
AG SKU | Standard_Small | Standard_Small | Standard_Small | - | -
Autoscaling | false | false | false | true | true
Minimum Scale Units | - | - | - | 1 | 2
AG Capacity/ Maximum  Scale Units | 1 | 2 | 2 | 15 | 30
DB New | New | New | New | New | New
DB Type | SQLAZURE | SQLAZURE | SQLAZURE | SQLAZURE | SQLAZURE
Edition | Serverless | Serverless | Standard | Standard | Premium
RSO Name/Capacity | 1 | 4 | S4 | S12 | P1
minCapacity | 0.5 | 0.5 | - | - | -
Max Size | 10737418240(10 GB) | 107374182400(100 GB) | 536870912000(500 GB) | 1099511627776(1 TB) | 1099511627776(1 TB)

These 5 shoe Sizes must be added to the Regression Test Suite in the Azure Template Release pipeline.

New Database Options to support Development size
Create a new database server and instance like one described inEvernote: https://www.evernote.com/shard/s13/client/snv?noteGuid=b2aa6ce9-6bf9-4c7b-86a9-7a505e99071c&noteKey=b9307b94e6bc13ba&sn=https%3A%2F%2Fwww.evernote.com%2Fshard%2Fs13%2Fsh%2Fb2aa6ce9-6bf9-4c7b-86a9-7a505e99071c%2Fb9307b94e6bc13ba&title=Accolite%2BAzure%2BDatabase%2BSetup

The instructions above relate to the portal settings. Its not clear how to map those to parameters in the template. Here is a comparison of what the template currently does on the left and what the instructions above create on the right. The significant values are highlighted. The rest are either derived values, unique values, temporary values or already allowed for with existing parameters like the maxSizeBytes...

![kdiff3_2020-11-17_15-56-59](https://user-images.githubusercontent.com/4089160/99750148-f6ddf580-2b33-11eb-8ee2-e2aa6e8eeb78.png)

So some investigation is required by the programmer to ensure that the template changes may create a resource like the resource on the right. Use Azure Resource Explorer to investigate.

Make sure the apiVersion is up to date otherwise Serverless is not supported.

Some background on what a particular vcore SKU means:
https://docs.microsoft.com/en-us/azure/azure-sql/database/resource-limits-vcore-single-databases

Edition parameter will have an allowed value of `Serverless` added.

requestedServiceObjectiveName parameter will be hidden. Instead a new parameter will be shown Capacity which will have allowed values of 1, 2, 4, 6, 8, 10, 12, 14, 16, 18 20, 24, 32, 40. In the UI, only these values are selectable when Edition = Serverless.

It looks like the current template properties of :

             "properties": {
                "edition": "[parameters('edition')]",
                "requestedServiceObjectiveName": "[parameters('requestedServiceObjectiveName')]"
             }

Have been replaced by:
“name”
“capacity”

So for the example above, the properties may have these values:
“Name”: “GP_S_Gen5”,
“Capacity”: “1”

So when the Parameter Edition = “Serverless”, then the name = “GP_S_Gen5”, and the capacity = [the Capacity parameter value].

And “kind” is NOT used at all in the template. It is a derived value.

This link is the basis of the above conclusions. It may be wrong: https://docs.microsoft.com/en-us/answers/questions/135105/arm-template-for-serverless-azure-sql-database.html

And
“minCapacity”: “a number” is required. Default value = 0.5. Its valid values are as follows:
0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 3, 4, 5, 6, 8, 10, 12, 14, 16, 18, 20, 24, 32, 40

minCapacity has a range of valid values. It must not be greater than the maxCapacity. This must be coded.

It also has more complex rules for the smallest value it may be. For example, when maxCapacity = 40, the smallest minCapacity = 5. These more complex rules do not need to be implemented. It will be up to the user to know the rules. This link describes the range: https://docs.microsoft.com/en-us/azure/azure-sql/database/resource-limits-vcore-single-databases

It is required that these differing properties are implemented using conditional resources based on the value of Edition = “Serverless”.

**Comment by robe070** [comment]
The hint for minCapacity should be:
The Minimum Capacity must be less than or equal to the Capacity. The Minimum Capacity must also be greater than a set value which is dependent on the Capacity. [Learn more about SQL Database resource limits, and in particular the vCore (Capacity) range](https://docs.microsoft.com/en-us/azure/azure-sql/database/resource-limits-vcore-single-databases)

**Comment by ashutosh-kumar1** [comment]
@robe070, Below are the findings and possible implementation changes that I have found till now regarding issue #17/18
1. Unable to hide the blade. It is only possible to hide the elements of the blade but the empty blade looks bad in this case.
2. I am unable to add conditions in the createUiDefinition file(especially the if condition) in most of the fields. If that was possible things would be easier.
3. For custom, it will not be possible to keep the same data for the previously selected type(developer, small, etc). We can have a set of default values for custom and it will be set in the fields.
4. There will be a lot of variable declarations and condition implementations in the mainTemplate file as for each type we will have different variables/objects.

For points 1 & 2, can you post the queries to the best person available in the Microsoft team, for a faster response?

**Comment by robe070** [comment]
We need to have a meeting to discuss your findings. Please arrange a meeting as soon as you can today.

**Comment by edgarwharton** [comment]
@robe070 @ashutosh-kumar1 

1. What would be the downside of duplicating the UI 6 times for each of the shoe sizes + custom? Would this effect any execution of the environment? Would this cause issues with the release pipeline when making any changes? 
 
Perhaps I am not viewing this properly, but from what I can see there are [Logical Functions](https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/create-ui-definition-logical-functions) that can be used in  `createUIdefinition `such as "If."

Additoinal resources: 

-[Create Flexible Arm Templates Using Conditions and Logical Functions]( https://azure.microsoft.com/en-us/blog/create-flexible-arm-templates-using-conditions-and-logical-functions/)
-[Sample Template](https://gist.github.com/krnese/59f3f2668ecd9b02402bf31bbc6bf253)

Is it that the JSON data types being used do not support the logical functions?

**Comment by ashutosh-kumar1** [comment]
@robe070, Please validate of this createUiDefinition file is up to the expectation for the Dev show size.
[createUiDefinitionDev.txt](https://github.com/robe070/cookbooks/files/5640754/createUiDefinitionDev.txt)

Please note it does not contain Ajitesh's code for now. Also, the values for blades which should not be visible to the user either have default values in the template or are hard-coded in the output section of the createUiDefinition file.

**Comment by robe070** [comment]
Installation Options blade needs to be shown, with defaults. They are part of maintaining the stack.

The rest looks good!

**Comment by robe070** [comment]
Actually, I wonder what happens when you re-deploy a Solution Template? Does it show the UI? Or does it only work of the template? I'll check right now if I can.

**Comment by robe070** [comment]
No there isn't one that I can see. I'll create one from the AMP Solution Template and re-deploy it. 

If its just the template, the Installation Options blade is not required.

**Comment by ashutosh-kumar1** [comment]
> Installation Options blade needs to be shown, with defaults. They are part of maintaining the stack.
> 
> The rest looks good!

Displaying the blade will enable the user to edit it. Are we sure we want to show it? We are providing all blades in the custom template. If we don't hide the two blades then I feel it will behave the same as the custom template where we have pre-filled values and we can just go ahead and click next!

**Comment by robe070** [comment]
I have tested the re-deployment and it does not show the UI again, so there is no point in showing the Installation Options blade. So, leave it as it is.

**Comment by ashutosh-kumar1** [comment]
Hi @robe070 ,
I have created multiple createUiDefinition files for different shoe sizes and created a PR : https://github.com/lansa/azure-quickstart-templates/pull/25,
I have also updated the CI pipeline to create zip files for all the shoe sizes. Please review: https://dev.azure.com/VisualLansa/Lansa%20Azure%20Scalable%20License%20Images/_build/results?buildId=591&view=artifacts&pathAsName=false&type=publishedArtifacts
You can try deployment using any zip and approve the PR.
Please provide me your feedback if you need any further modifications

**Comment by robe070** [comment]
The `Resource Group Name` parameter should be called `Key Vault Resource Group Name`.

The default for `Key Vault Enabled` should be `true`.

There needs to be something to identify that its a particular shoe size. A label at the top of each blade? e.g `Development Stack`

I'd like to see the input for the regression tests being the output from the Sandbox. Precisely. Just copy it as it is. Ensure that the values will always be unique. Names may be changed of course but all settings must be kept as is.

**Comment by robe070** [comment]
Large Stack
These values seem to be incorrect:
```json
"applicationGatewaySkuTier": {
    "value": "Standard_v2"
  },
  "agpublicIpSku": {
    "value": "WAF_v2"
  },
```

All the remainder Sandbox Outputs seem to be match the table above.

**Comment by robe070** [comment]
Code complete only

**Comment by ashutosh-kumar1** [comment]
@robe070, Template CI and CD pipeline also modified as per the requirements.
The CD pipeline is restructured to run 5 parallel stages containing 2-3 jobs each. This is done to reduce the overall regression time and will also allow running only that particular stage where the build has failed. The stages could have been further broken but that might result in an unexpected failure as 13 separate stages would create 39 IPs while the maximum cap for IP creation in a region is 40.
Please provide your feedback on the same.

**Comment by ashutosh-kumar1** [comment]
Release-44 is in progress now with the latest changes.

**Comment by robe070** [comment]
> The CD pipeline is restructured to run 5 parallel stages containing 2-3 jobs each. This is done to reduce the overall regression time and will also allow running only that particular stage where the build has failed. The stages could have been further broken but that might result in an unexpected failure as 13 separate stages would create 39 IPs while the maximum cap for IP creation in a region is 40.

The maximum number of ips may be increased quite easily. But its passable as it is right now. 

I'll create an Issue to break this up further. To be done in a later PRD. The quicker the better. Especially when changing the pipeline

**Comment by robe070** [comment]
Development Stack
1. Does not have a default value for `Key Vault Enabled`. Set it to `True`.

**Comment by ashutosh-kumar1** [comment]
> Development Stack
> 
> 1. Does not have a default value for `Key Vault Enabled`. Set it to `True`.

Updated the default value to True and raised a PR: https://github.com/lansa/azure-quickstart-templates/pull/26
Please review and merge.

**Comment by ashutosh-kumar1** [comment]
Also, w.r.t the template regression pipeline, requesting you to cancel all/any deployment which is in the Manual Intervention stage. This should allow the upcoming release to pass and wait at Manual Intervention stage.
