### ISSUE TITLE
P2 Required reading for all devs working on the template

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#19]
Refer PRD section 14 Phase 2 Guidance

This is a new process for LANSA so direct guidance on how to develop a Solution Template is not possible. Nonetheless, essentially a Solution Template is an Azure Quickstart Template with added features. 

So you will need to either already be an expert in Azure Quickstart Templates and Solution Templates or you will need to educate yourselves and raise your skill level to that of an expert. Liaising with the Architect and frequently pushing changes, at least weekly, to the git repo are essential to ensure that Phase 2 continues along the intended track.

There will be a daily meeting with the architect until it needs to change.

This describes the current structure of the Azure Quickstart Template and the process of taking it as it is and publishing it as a Solution Template. It is meant for information only to get an overview of what is currently there and how the template needs to be altered to be admissible to Marketplace. It is NOT the specification of the work required.
[Marketplace Sample](https://github.com/Azure/azure-quickstart-templates/tree/master/100-marketplace-sample)

It is mandatory to watch [Building Solution Templates and Managed Applications for the Azure Marketplace](https://channel9.msdn.com/Events/Build/2018/BRK3603). It is expected that the guidance provided in the video will be followed exactly unless exceptions have been authorized. 

One of the main tasks in Phase 2 is to integrate the 'tests' folder that is in the Azure Quickstart Template repository into the robe070/cookbooks repository. The tests folder has been redesigned and is now called [the ARM Template Test Toolkit](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/test-toolkit). That link describes the automated testing that needs to be achieved in Phase 2. Both being able to run these tests on a developer's machine and integrated into Azure Pipelines.

Other reference documents are provided below. At least read the contents of every document to know what help is available to you.

Document | URL
-- | --
ARM template test toolkit | https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/test-toolkit
Azure Solution Templates Documentation (PDF) | https://drive.google.com/open?id=1-ZUFfaEsIW8G9lWAQatlR3zmQiM3-A8P
Azure Quickstart Templates | https://github.com/Azure/azure-quickstart-templates
Azure Quickstart Template Best Practices | https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md
Azure Resource Manager Template Toolkit (arm-ttk) | https://github.com/Azure/arm-ttk
Template Deployment Scripts | https://github.com/Azure/azure-quickstart-templates/blob/master/Deploy-AzureResourceGroup.ps1
UI Testing SideLoad Scripts | https://github.com/Azure/azure-quickstart-templates/blob/master/SideLoad-CreateUIDefinition.ps1
Template Reference Docs | https://docs.microsoft.com/en-us/azure/templates/
CreateUIDefinition Docs | https://docs.microsoft.com/en-us/azure/managed-applications/create-uidefinition-functions
Template Language Expressions | https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions
Azure PowerShell | https://docs.microsoft.com/en-us/powershell/azure/?view=azps-4.4.0
Azure CLI | https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest
Visual Studio Code Extension | https://marketplace.visualstudio.com/items?itemName=msazurermtools.azurerm-vscode-tools

**Comment by VarunChopraAccolite** [comment]
hi @robe070 
we can move this ticket to Wiki and we can refer from there.

**Comment by robe070** [comment]
Moved to Wiki
