### ISSUE TITLE
Add the scalable licences to the VM using the Key Vault Secrets

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#2]
The PRD describes the following objective in section 6.1.4:
_Following Azure Security Best Practices and utilizing the Azure Key Vault, design a secure mechanism to store and retrieve the Scalable License Certificates. To be designed by the architect before Phase 1 begins._
Here is a document that contains the design. And in particular the change required in the script. It will be augmented later with the Splash Screen design.
Refer here for details: https://www.dropbox.com/s/4vm4vep81a7u7r5/Cloud%20Deployment_%20Azure%20Scalable%20Images_Architect%20Prereqs%20-%20Google%20Docs.pdf?dl=0

**Comment by robe070** [comment]
Test comment from Slack

**Comment by mricha** [comment]
hi @robe070 
Thank you for your comments. I had checked in the code changes that adds the secret using the `Add-AzVMSecret`.
`TestLicense.ps1` script checks for license in the registry. I believe the changes are to be done in the `TestLicense.ps1` file to accurately verify the certificates (involves clarification on the registry and private keys during the script execution). Also, I feel that without the registry changes the application might not work as expected.
![Certs](https://user-images.githubusercontent.com/28262916/88389478-37bb3d00-cdd4-11ea-835c-c8c9e85e786a.png)
We see the certificate is added using `Add-AzVMSecret` (not marked as exportable though `hasPrivateKey `is `true `and the private key is displayed as `null`). Also, I did no additional changes for the registry entry. 
![image](https://user-images.githubusercontent.com/28262916/88389402-15292400-cdd4-11ea-9e6f-0b29b5c2733e.png)
Please provide your valuable inputs to below.
1. License Key Check using registry can be bypassed for azure or we can create registry entry manually using the secret?
    - we prefer to bypass if no dependency of Application
2. Certificate has no exportable option in `Add-AzVMSecret`, we can verify that the certificate exists in the `TestLicense `for Azure, 
    - do you wanted us to manually add the certificate with exportable true?

Also, let us know if the below clarification is relevant to the context:
1. Does the application consumes the certificate or does it look for the registry keys as well.

`TestLicense.ps1` script Output:
![LicenseTestsResults](https://user-images.githubusercontent.com/28262916/88389638-794be800-cdd4-11ea-9ef8-19b7d28c76d4.png)

Please find the link to the commit below for your reference. 
https://github.com/robe070/cookbooks/commit/e531579c7b15e10d507f795378c7ddff278220d9

**Comment by robe070** [comment]
> We see the certificate is added using `Add-AzVMSecret` (not marked as exportable though hasPrivateKey is true and the private key is displayed as null).

This is correct.

> Certificate has no exportable option in` Add-AzVMSecret`, we can verify that the certificate exists in the TestLicense for Azure,
do you wanted us to manually add the certificate with exportable true?

No. Its perfect as it is.

> Does the application consumes the certificate or does it look for the registry keys as well.

It does both. Or more accurately, the registry keys are used when the application is installed to enable access to the certificate for the web user. When the LANSA application runs as Web User, it loads the certificate using its unique identification . The fact it can be loaded confirms the license check.

So, In `CreateLicense`, you need to skip the part that uses the pfx files to install the certificate, because that has already been done by using `Add-AzVMSecret`. Just do the part that sets up the registry.

That is, you need to only do this code for AWS:

```
            #####################################################################################
            Write-Host "$(Log-Date) $dnsName_ : install license"
            #####################################################################################
            $mypwd = ConvertTo-SecureString -String $password_ -Force -AsPlainText
            Import-PfxCertificate -FilePath $licenseFile_ cert:\\localMachine\\my -Password $mypwd | Write-Host
```

**Comment by mricha** [comment]
hi @robe070 
Thanks for your guidance and support. I am able to build the image successfully with the recent changes. Please review and let me know your comments.

![image](https://user-images.githubusercontent.com/28262916/88564713-2b8fe380-d051-11ea-947f-14662d3814a3.png)

**Comment by robe070** [comment]
Looks good. The only question I have is whether this VM was created from the image you built?

And you should be using the production name for the image as I indicated previously. One person needs to be using the production name, and that seems to be you. => `w12r2d-14-2-10`

**Comment by robe070** [comment]
And once you've built the correctly named image, keep the SAS URL for submitting to Azure Marketplace
