### ISSUE TITLE
P3 Setup Image Pipeline base

### ISSUE THREAD

**Issue by VarunChopraAccolite** [robe070/cookbooks#22]
Design a pipeline refer the wiki page for more information, need to add subtasks.

**Comment by VarunChopraAccolite** [comment]
Hi @robe070 
Please find below the error message when configuring the pipeline. I might need admin access (temporarily) to configure the pipeline.

[https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#integrate-using-the-github-app](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#integrate-using-the-github-app)

[https://developercommunity.visualstudio.com/content/problem/200262/vsts-cicd-from-github-not-working.html](https://developercommunity.visualstudio.com/content/problem/200262/vsts-cicd-from-github-not-working.html)

> Unable to configure a service on the selected GitHub repository. This is likely caused by not having the necessary permission to manage hooks for the selected repository.

![image](https://user-images.githubusercontent.com/24430923/89255302-04cc4100-d63f-11ea-8e59-a0b49338d02a.png)

**Comment by robe070** [comment]
@VarunChopraAccolite If it is a personal repository, only the repository owner can create hooks. So what do I need to do?

**Comment by robe070** [comment]
@VarunChopraAccolite Can we have a short discussion to go through the Pipeline discussion paper and confirm the understanding please. Either at 4 pm today, or at 5:30 pm today. Maximum 30 minutes. Times in AEST. So, 11:30 am IST or 1 pm IST.

**Comment by robe070** [comment]
@VarunChopraAccolite And email me with a high priority email to have the highest chance of me seeing the invitation you create to Google Meet.

**Comment by VarunChopraAccolite** [comment]
Hi @robe070 
Thanks, we can connect at the earliest 11:30 IST. I will share the invite.

**Comment by VarunChopraAccolite** [comment]
Hi @robe070 
As discussed, I will create a standard generic PS Script that accepts below parameters with logic to select all/any image for build and testing. The PS Script might be called multiple times by the Powershell tasks without the loop.

```
-VersionText 'w12r2d-14-2-10' `
-VersionMajor 14 `
-VersionMinor 2 `
-AmazonAMIName "2012-R2-Datacenter" `
-GitBranch "feature/azure-images" `
-Cloud "Azure" `
-Win2012 $true 
```

**Comment by robe070** [comment]
Refer #4 for how the VersionText parameter is derived and thus the values required for most of the other parameters.

**Comment by robe070** [comment]
@VarunChopraAccolite I've updated the Wiki Discussion page. My edits are marked with ~~strike out~~ for items to remove and `inline code marks` for either comments or suggested replacements. We probably should discuss first thing on Wednesday. I'm available from 2:30 am AEST (10 am IST?) until 4:45 pm. Please choose a time that suits you.

**Comment by VarunChopraAccolite** [comment]
Hi @robe070 
Sure, let's connect 10 AM IST. I will share an invite across.

**Comment by VarunChopraAccolite** [comment]
hi @robe070 
The Image Build Pipeline and Release Pipeline is up and running. Let me know if you need any further changes.

Thanks
