### ISSUE TITLE
Use NewOrExisting pattern for Application Gateway public ip address in template

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#25]
Note: There are 3 public ip addresses. Only the Application Gateway public ip address needs to be altered. This is because it is the address of the application that is being deployed. Whereas the other 2 are for troubleshooting the VMs.

**Comment by knagasekharreddy** [comment]
Hi @robe070 where i need to find storage account in `mainTemplate.json` & `CreateUIDefination.json` files there is no Storage account please help on this.

**Comment by robe070** [comment]
There are no storage accounts. I have modified the title only. The description is still correct.

**Comment by robe070** [comment]
@ashutosh-kumar1 The latest template frpm PR template.#21 commit ID 2505f64 is not behaving like I would expect:
![image](https://user-images.githubusercontent.com/4089160/100695709-e5bf9f00-33e5-11eb-94eb-e84671a92bcc.png)

We need to discuss this. And maybe there are later changes which fix this.

**Comment by robe070** [comment]
Code complete only
