### ISSUE TITLE
P3 Use a separate resource group for each Azure Image to ease deletion

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#26]
Modify the `Bake-Ide-Msi.ps1` script to create a resource group based on the VersionText, if it doesn't already exist.

This is important for the pipeline so that it may be cleaned up after building the image.

`Bake-Ide-Msi.ps1` must not delete the resource group itself. During development its up to the developer to delete when appropriate. The pipeline will delete it on successful completion. Note that the image must be placed in the existing BakingDP resource group so that it is not deleted.

The KeyVault will stay in BakingDP 

The image baking resource groups will be named `BakingDP-<VersionText>`. E.g. `BakingDP-w12r2d-14-2-10`

**Comment by robe070** [comment]
@VarunChopraAccolite  FYI

**Comment by VarunChopraAccolite** [comment]
hi @robe070 
I had modified the script as discussed to use the VmResourceGroup and ImageResourceGroup. Image and the KeyVault uses the ImageResourceGroup.
Please find the SS of the output.

![image](https://user-images.githubusercontent.com/24430923/89984197-9fa7c980-dc96-11ea-91ca-9627c82aa0d4.png)
![image](https://user-images.githubusercontent.com/24430923/89984251-b64e2080-dc96-11ea-9eb4-8a9a9ff670e9.png)

**Comment by robe070** [comment]
The changes are very good. Exactly as discussed. I have also tested that, with the VM resource group deleted, that a VM may be created from the Image successfully.
