### ISSUE TITLE
P3: Add a flag to disable the MessageBox for pipeline runs

### ISSUE THREAD

**Issue by VarunChopraAccolite** [robe070/cookbooks#29]
Bake-Ide-Ami script should accept a [switch] Pipeline to handle the scenarios relevant to the pipeline build. This issue covers a scenario to suppress the Messagebox for the Pipelines.

**Comment by VarunChopraAccolite** [comment]
hi @robe070 
Please review the changes done using the [switch] parameter type as discussed and let me know your comments.

https://github.com/robe070/cookbooks/commit/775471017ecab61fe089288d74258a749023e33f

**Comment by robe070** [comment]
Changes are correct in principle
