### ISSUE TITLE
Remotely execute the script install-base-sql-server.ps1

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#3]
One of the tasks is to automate the baking of the image. And there is currently a prompt which requires manual intervention. This exists because the script installs a Windows Update and that is not permitted using Remote Powershell.
After talking with Harish last night I wondered if the Az Module provided a cmdlet which would execute a powershell script in the VM. And there is. So you will replace the manual prompt by using this cmdlet:
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/run-command.

This is optional for Phase 1 and required for Phase 2.  I suggest you implement for phase 1  because it sounds simple to do and will speed up your work.

**Comment by ashutosh-kumar1** [comment]
Hi @robe070,
We tried automating the baking image step both using the remote PowerShell and the cmdlet, but failed.
We altered line-457 of 'bake-ide-ami.ps1' file: 
`$dummy = MessageBox "Run install-base-sql-server.ps1. Please RDP into $Script:vmname $Script:publicDNS as $AdminUserName using password '$Script:password'. When complete, click OK on this message box"`
 to the below mentioned code: 
- For Executing it through cmdlet:

`Invoke-AzVMRunCommand -ResourceGroupName $svcName -Name $Script:vmname -CommandId 'RunPowerShellScript' -ScriptPath <local path of script>`
This would not show any error during execution, but on verifying the temp folder, the windows installer & update files were not downloaded.

- For executing it through remote powershell:

`$password = convertto-securestring -AsPlainText -Force -String $Script:password
$cred = new-object -typename System.Management.Automation.PSCredential -argumentlist $AdminUserName,$password
Invoke-Command -Computer $Script:publicDNS -Scriptblock { C:\lansa\scripts\install-base-sql-server.ps1 } -Credential $cred`

This executed the file on the remote machine but failed with an error code 5 on the the below mentioned line of 'install-base-sql-server.ps1' file (Please find screenshot attached):
**line-64:** `$p = Start-Process -FilePath $installer_file -ArgumentList @('/quiet') -Wait -PassThru`

![Windows update error](https://user-images.githubusercontent.com/67790012/87795125-3bdfdb80-c865-11ea-91a3-8fad666954f8.png)

**Could you suggest to us where we are going wrong?**

**Comment by robe070** [comment]
Firstly, as per the PRD, every line of the scripts that does not capture the result of a cmdlet in a variable is required to | Out-Default | Write-Host.
If you do that you will see output from the command.

Secondly, as I discussed with you the first time we were on a call with just the two of us, the reason this script is run manually is because you cannot run Windows Updates in a remote PowerShell session.

Invoke-AzVMRunCommand is documented to be able to run Windows Updates. I would have done the following:

1. Start with the Azure Portal and ensure that I can run ipconfig command using the cmdlet on a simple VM created in the Portal.
2. Run ipconfig on that simple VM through PowerShell
3. Run ipconfig on that simple VM in bake-ide-msi.ps1
4. Run ipconfig on the baking VM in bake-ide-msi.ps1
5. Run the script on the simple VM through PowerShell and work through issues
6. Run the script on the baking VM in bake-ide-msi.ps1 and work through issues

**Comment by ashutosh-kumar1** [comment]
Code committed to branch feature/azure-images with commit message : CCS-163204: Remotely execute the script install-base-sql-server.ps1
