### ISSUE TITLE
P2: Resolving Template error messages using the ARM TTK

### ISSUE THREAD

**Issue by VarunChopraAccolite** [robe070/cookbooks#30]
Please find attached the log of the report after running the ARM TTK. I will link the steps to run the ARM TTK in Development environment in the Wiki. Below tests are failing that needs attention.

```
[-] apiVersions Should Be Recent (315 ms) 
##[error]        Microsoft.Sql/servers uses a preview version ( 2018-06-01-preview ) and there are more recent versions available.
        Valid Api Versions:
        2019-06-01-preview

##[error]        Api versions must be the latest or under 2 years old (730 days) - API version 2018-06-01-preview of Microsoft.Sql/servers is 796 days old
        Valid Api Versions:
        2019-06-01-preview

##[error]        Microsoft.Sql/servers/databases uses a preview version ( 2018-06-01-preview ) and there are more recent versions available.
        Valid Api Versions:
        2019-06-01-preview

##[error]        Api versions must be the latest or under 2 years old (730 days) - API version 2018-06-01-preview of Microsoft.Sql/servers/databases is 796 days old
        Valid Api Versions:
        2019-06-01-preview

##[error]        Microsoft.Sql/servers/firewallRules uses a preview version ( 2018-06-01-preview ) and there are more recent versions available.
        Valid Api Versions:
        2019-06-01-preview

##[error]        Api versions must be the latest or under 2 years old (730 days) - API version 2018-06-01-preview of Microsoft.Sql/servers/firewallRules is 796 days old
        Valid Api Versions:
        2019-06-01-preview

```

[BestPracticeTests-Template.txt](https://github.com/robe070/cookbooks/files/5032519/BestPracticeTests-Template.txt)

**Comment by VarunChopraAccolite** [comment]
Adding the wiki for running ARM TTK locally.
[https://github.com/robe070/cookbooks/wiki/Lansa-Templates---Validation-policy-using-ARM-TTK](https://github.com/robe070/cookbooks/wiki/Lansa-Templates---Validation-policy-using-ARM-TTK)

**Comment by robe070** [comment]
I was going to describe how to determine what the latest API version is. But I notice that it tells you what it is! So, just put that in the template. A simple change to 6 locations in the template.

And here is the process if there is a defect in the API version given, when an older version may need to be used:

List Template API Versions

```Powershell
((Get-AzResourceProvider -ProviderNamespace <Namespace>).ResourceTypes | Where-Object ResourceTypeName -eq <ResourceType>).apiversions
```

e.g. When the template contains this type:

"type": `Microsoft.Network/publicIPAddresses`

then this is what you use to get the api versions:

```Powershell
((Get-AzResourceProvider -ProviderNamespace Microsoft.Network).ResourceTypes | Where-OBject ResourceTypeName -eq publicIPAddresses).apiversions
```

I'll do the first error reported by the pipeline above. I've **bolded** the text thats significant:

> ##[error]        **Microsoft.Sql/servers** uses a preview version ( 2018-06-01-preview ) and there are more recent versions available.

```Powershell
PS C:\Users\Robert.SYD\Documents\GitHub\cookbooks_scalable\Tests> ((Get-AzResourceProvider -ProviderNamespace **Microsoft.sql**).ResourceTypes | Where-OBject ResourceTypeName -eq **servers**).apiversions

2020-02-02-preview
2019-06-01-preview
2018-06-01-preview
2017-10-01-preview
2017-03-01-preview
2015-05-01-preview
2014-04-01-preview
2014-04-01
2014-01-01
```

And I immediately notice that the suggestion in the error message is out of date. You must use `2020-02-02-preview`. So, you must go through the process to determine the latest API version yourself for each of the other 5 errors.
