### ISSUE TITLE
P3 Extend the Image Release Pipeline to build six images in the Build Stage

### ISSUE THREAD

**Issue by VarunChopraAccolite** [robe070/cookbooks#31]
The Image Release Pipeline builds a single image, use the table provided in the https://github.com/robe070/cookbooks/issues/4 to extend the build process to the six images.

**Comment by VarunChopraAccolite** [comment]
Also, add control to build all images or selected ones.
We define the below variables and use them in to control the tasks in the Pipeline.
```
Build-all -> If set to 'True' will build all the images
Build-<sku> - If set to 'True' will build only the selected ones
```
**Example:**
Below configuration builds for w-12r2d-14-2 and w-16d-15-0

![image](https://user-images.githubusercontent.com/24430923/89866909-f6959c00-dbcd-11ea-888e-ec85a180275a.png)

**Comment by robe070** [comment]
Good idea.

**Comment by VarunChopraAccolite** [comment]
Hi @robe070 
I had extended the build stage of the release pipeline in the build pipeline itself that publishes the SAS URL as Artifact. We have completed the build pipeline for six images, and we can close this one out. Let me know if we need to work on any additional tasks wrt this issue.
