### ISSUE TITLE
P2 Allow template to be used to test new images

### ISSUE THREAD

**Issue by VarunChopraAccolite** [robe070/cookbooks#33]
The purpose of this task is to allow for images in all stages of development, test and production to be used by the template.

This issue is required to be done at the earliest oppourtunity so that the template may be used to test the new images. The template will not be published yet, so it will need to be downloaded as a raw file from the GitHub repo. These changes should be made in `lansa/azure-quickstart-templates` `feature/azure-images`.

It must also incorporate the ability to use a Custom Image instead of a Marketplace image, again, so that a Custom Image may be tested by the pipeline. This will involve extending the template sample provided below to prompt for Marketplace Image (default) or Custom Image. And provide extra parameters to specify those required for a Custom Image.

Also change the Offer and SKU selection to get the SKUId and OfferId based on the user's selection of the OS, Lansa Version and Release State.

**Sample Input 1**
![image](https://user-images.githubusercontent.com/24430923/89529696-c97e6d80-d80a-11ea-91e7-cb60f4a4836f.png)
**Sample Output 1**
![image](https://user-images.githubusercontent.com/24430923/89529717-d3a06c00-d80a-11ea-8cf3-06751fc77a56.png)

**Sample Input 2**
![image](https://user-images.githubusercontent.com/24430923/89529748-de5b0100-d80a-11ea-8371-b8694e093d85.png)
**Sample Output 2**
![image](https://user-images.githubusercontent.com/24430923/89529780-ea46c300-d80a-11ea-8d95-accc02a3f848.png)

Refer the section 21.1 in the PRD.
```
{
	"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
	"contentVersion": "1.0.0.0",
	"parameters": {
		"osName": {
			"type": "string",
			"allowedValues": [
				"Windows Server 2019",
				"Windows Server 2016",
				"Windows Server 2012"
			],
			"defaultValue": "Windows Server 2019",
			"metadata": {
				"description": "Choose the Windows Server image version to use "
			}
		},
		"lansaVersion": {
			"type": "string",
			"allowedValues": [
				"V15 GA",
				"V14 SP2"
			],
			"defaultValue": "V15 GA",
			"metadata": {
				"description": "Visual LANSA Version"
			}
		},
		"imageReleaseState": {
			"type": "string",
			"allowedValues": [
				"Production",
				"Preview"

			],
			"defaultValue": "Production",
			"metadata": {
				"description": "Release state of the LANSA Scalable License image.The Preview release state is restricted to a very limited audience."
			}
		}
	},
	"variables": {
		"marketplaceSettings": {
			"Windows Server 2019": {
				"offer": "lansa-scalable-license",
				"version": {
					"V15 GA": {
						"sku": "win-2019-15-0"
					},
					"V14 SP2": {
						"sku": "win-2019-14-2"
					}
				}
			},
			"Windows Server 2016": {
				"offer": "lansa-scalable-license",
				"version": {
					"V15 GA": {
						"sku": "win-2019-15-0"
					},
					"V14 SP2": {
						"sku": "win-2019-14-2"
					}
				}
			},
			"Windows Server 2012": {
				"offer": "lansa-scalable-license",
				"version": {
					"V15 GA": {
						"sku": "win-2019-15-0"

					},
					"V14 SP2": {
						"sku": "lansa-scalable-license-14-2"
					}
				}
			}
		},
		"isPreview": "[equals(parameters('imageReleaseState'), 'Preview')]"
	},
	"resources": [],
	"outputs": {
		"offerId": {
			"value": "[concat(variables('marketplaceSettings')[parameters('osName')].offer, if (variables('isPreview'), '-preview', ''))]",
			"type": "string"
		},
		"skuId": {
			"value": "[variables('marketplaceSettings')[parameters('osName')].version[parameters('lansaVersion')].sku]",
			"type": "string"
		}
	}
}
```
Refer https://github.com/robe070/cookbooks/issues/4 for parameter mapping.

**Comment by robe070** [comment]
Prior to implementing this issue, Issue #24 needs to be completed.

**Comment by robe070** [comment]
I've edited the initial comment to clarify the requirement and remove the prereq of #24

**Comment by ashutosh-kumar1** [comment]
@robe070 I have modified the code for lansa/azure-quickstart-templates but was unable to push it to the branch feature/azure-images as I do not have the permission for the same. Meanwhile, I have pushed the changes to my fork, please refer: 
https://github.com/ashutosh-kumar1/azure-quickstart-templates/commit/eb1a3d277d208a59d2cb25dc865eced7cc1eaa7b
I have mapped the SKU as per the table mentioned in issue #4. Please verify the code and provide me the review comments. I will be able to push the code in lansa/azure-quickstart-templates once you provide me access to it.

After completing the changes I also tested the deployment of both marketplace as well as custom image by modifying the test.parameters.json file with the desired inputs. I have also committed the modified file with sample values in the feature/azure-images branch, please refer: https://github.com/robe070/cookbooks/commit/9b01c8db70fc3d76257899ca562844e3f940f80c

Below are the log and snapshot of both the images.
Custom image log file:  [custom image deployment log.txt](https://github.com/robe070/cookbooks/files/5042976/custom.image.deployment.log.txt)
Custom image portal screenshot:
![custom image deployment](https://user-images.githubusercontent.com/67790012/89674970-b8b32200-d906-11ea-8ae2-a8426a059b8a.PNG)

Marketplace preview image logs: 
[marketplace image deployment logs.txt](https://github.com/robe070/cookbooks/files/5042977/marketplace.image.deployment.logs.txt)
Marketplace image portal screenshot:
![marketplace image deployment](https://user-images.githubusercontent.com/67790012/89675020-d97b7780-d906-11ea-9073-dbb44c8ca35d.PNG)

Please provide your feedback if anything else need to be done for this issue.

**Comment by robe070** [comment]
@ashutosh-kumar1  I've given you push access to the lansa/azure-quickstart-templates repo.

The changes look OK in principle. The resultant VMSS are deploying the correct images.

You seem to have copied the VMSS resource definition entirely thus duplicating many lines of code creating a maintenance issue. You need to put the condition at the lowest level possible. Its currently too high.

Every parameter thats involved in this choice should indicate which imageSource its relevant to. Like the New/Existing DB choice does. And that needs to be thought through. Its unlike New/Existing DB in that the end user does not have a choice of imageSource. It must always be Marketplace and also never Preview. So I think the best way to resolve that is for me to edit the template once you have pushed it to the lansa repo.

**Comment by robe070** [comment]
>You seem to have copied the VMSS resource definition entirely thus duplicating many lines of code creating a maintenance issue. You need to put the condition at the lowest level possible. Its currently too high.

@ashutosh-kumar1 @VarunChopraAccolite Varun has spoken to me about the need to duplicate the code. This post should solve it:
https://stackoverflow.com/questions/45410686/using-conditional-if-statements-in-arm-templates-for-properties

So you don't use the Condition property. Instead you specify the value of the property as an `If` statement. Note the value for the property when you don't need it is `json('null')`

**Comment by ashutosh-kumar1** [comment]
@robe070, Thanks for the help. I went through the link and was able to replace the copied code with if condition. I have modified the JSON file and committed it after verifying that it worked properly.
Please review: https://github.com/lansa/azure-quickstart-templates/commit/cce18c1da9c656931937e817962b9e24a64834ce
