### ISSUE TITLE
P2 Create an initial Solution Template submission to Azure MarketPlace

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#35]
The purpose of this issue is to provide, at the earliest oppourtunity, a submission to AMP that is valid, so that basic issues of publishing a Solution Template may be solved. The `CreateUIDescription.json` file may be as simple as necessary to pass the tests.

Initial submissions to AMP can take a number of weeks, hence the need to get the process started ASAP.

Ref: #24

**Comment by ashutosh-kumar1** [comment]
@rob, I have added the initial draft for createUiDefinition.json file with the mainTemplate.json file too. I was able to successfully deploy the template using the output of the createUiDefinition file. Attaching the output json: [output json.txt](https://github.com/robe070/cookbooks/files/5069412/output.json.txt)
I have also added the conditions to hide the database server name and database name when a new database is selected. Please execute the createUiDefinition file and provide feedback if this change looks good. I will continue doing the other required changes as well.
Also, I had to enable the confirmation field for all the passwords as it was giving me errors while executing arm-ttk validation script.
