### ISSUE TITLE
P3 Demo of Azure image building and testing automation pipeline to validate that images have been built correctly.  

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#38]
Demo of Azure image building and testing automation pipeline to validate that images have been built correctly.

**Comment by VarunChopraAccolite** [comment]
hi @robe070 
The pipeline has the steps to Build the Image, runs the VM Tests. I am attaching the SS. Let me know if we need a discussion to close this one out. I am attaching the SS for the image building and testing automation pipeline.

![image](https://user-images.githubusercontent.com/24430923/90621830-e155e880-e231-11ea-8102-7d702de9fa8c.png)
![image](https://user-images.githubusercontent.com/24430923/90621890-f894d600-e231-11ea-9178-da85d4985617.png)
