### ISSUE TITLE
P4 Version specific splash screen for each Windows Server image i.e V14 SP2, V15 GA.

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#41]

**Comment by VarunChopraAccolite** [comment]
Hi @robe070 
We have modified the issue https://github.com/robe070/cookbooks/issues/47 to update the splash screen. Let us know if we require any further changes.
Thanks

**Comment by robe070** [comment]
A change is required to throw a fatal error if the Cloud/version combination does not exist. The current coding will hide the omission. Much better to know the issue has occurred upfront.

**Comment by VarunChopraAccolite** [comment]
Hi @robe070 
Please review the changes done and let us know your comments.
https://github.com/robe070/cookbooks/pull/55

**Comment by VarunChopraAccolite** [comment]
hi @robe070 
Please let us know if anything additional is required or we can close the ticket.
Thanks
