### ISSUE TITLE
P2 Test that template is using the expected image

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#48]
Modify template to output the image version and then check that the image in the VMSS matches the expected image: Offer, SKU and Version.

There is a useful tool that Azure provides to query the properties of a deployment: https://resources.azure.com/

Navigate down to your subscription, resource group and then to VMSS. You will find JSON similar to the extract at the end of this entry. You can see it clearly provides all the information we require to validate that the image is the correct one:

```
          "imageReference": {
            "publisher": "lansa",
            "offer": "lansa-scalable-license",
            "sku": "lansa-scalable-license-14-2",
            "version": "14.2.10"
          },
```

The Offer and SKU are already output because they are derived values..

To reference the version property in the outputs section use syntax similar to the following:

```
      "imageVersion": {
         "condition": "[not(variables('isCustomImage'))]",
         "type": "string",
         "value": "[reference(variables('dbvmssName')).storageProfile.imageReference.version]"
      },
```

And for completeness, also output the Custom Image inputs.

Following is the VMSS output from https://resources.azure.com/

```json
{
  "value": [
    {
      "name": "dbrobgyo4_0",
      "id": "/subscriptions/739c4e86-bd75-4910-8d6e-d7eb23ab94f3/resourceGroups/robg/providers/Microsoft.Compute/virtualMachineScaleSets/dbrobgyo4/virtualMachines/0",
      "type": "Microsoft.Compute/virtualMachineScaleSets/virtualMachines",
      "location": "australiaeast",
      "plan": {
        "name": "lansa-scalable-license-14-2",
        "publisher": "lansa",
        "product": "lansa-scalable-license"
      },
      "instanceId": "0",
      "sku": {
        "name": "Standard_B2ms",
        "tier": "Standard"
      },
      "properties": {
        "latestModelApplied": true,
        "vmId": "3d666b90-b6c9-426b-ab54-bb07fb74ea03",
        "hardwareProfile": {},
        "storageProfile": {
          "imageReference": {
            "publisher": "lansa",
            "offer": "lansa-scalable-license",
            "sku": "lansa-scalable-license-14-2",
            "version": "14.2.10"
          }
[snip]
    }
  ]
}
```

**Comment by VarunChopraAccolite** [comment]
Additional Notes:
Test the template output against parameters to the template. You have the SKU as a parameter and the version as a parameter. And the LANSA Major Version and Minor Version. Together you can validate against the output values.

**Comment by ashutosh-kumar1** [comment]
@robe070, I have a concern regarding using the version as a part of output.
As per mainTemplate.json, the version is hard-coded as 'latest'. Is there any change required in the template? ![version issue](https://user-images.githubusercontent.com/67790012/90595011-7db7c500-e209-11ea-89be-8206a4d52027.PNG)
I can see the output as 'latest' as well as the VM's Operating system section containing 'latest' in the version.

**Comment by robe070** [comment]
The template is correct. `latest` MUST be used. Its a validation check.

What have you put in the template output property? 
`SQLAZURE1VMSS` template does not contain the correct output code.
`SQLAZURE1-NS` template does not contain the correct output code.

This is required:
```
      "imageVersion": {
         "condition": "[not(variables('isCustomImage'))]",
         "type": "string",
         "value": "[reference(variables('dbvmssName')).storageProfile.imageReference.version]"
      },
```

**Comment by robe070** [comment]
I've found it in `rgak`

**Comment by ashutosh-kumar1** [comment]
Yes Rob, I have resource group 'rgak' created for the same. The output is:
![c2](https://user-images.githubusercontent.com/67790012/90599050-cc695d00-e211-11ea-84be-257368535719.PNG)
And the OS screenshot is:
![VM OS screenshot](https://user-images.githubusercontent.com/67790012/90599135-f1f66680-e211-11ea-96b9-781f42426dc2.PNG)
Now, the query I have is when can we see version value, not as 'latest' in the output and in the VM's OS section?
If it will always be 'latest' what is the need for version check?

**Comment by robe070** [comment]
Clearly what Azure Resource Explorer returns is what we need. You can only get the template value from within the template.

So can you get that value from Powershell? Is there a cmdlet to query the imageReference?

**Comment by ashutosh-kumar1** [comment]
The above mentioned output is obtained by using the below code:
```
"imageVersion": {
         "condition": "[not(variables('isCustomImage'))]",
         "type": "string",
         "value": "[reference(concat('Microsoft.Compute/virtualMachineScaleSets/', variables('dbvmssName'))).virtualMachineProfile.storageProfile.imageReference.version]"
      }
```

**Comment by robe070** [comment]
Correct.
And I've gone through all the GetAzVmss... cmdlets. Only one returns the value and its `latest`.
So, this can't be done this way. We would have to go back to running a PowershellScript on one of the VMSS  VM instances to return the registry value of VersionText. Like ImageVm.Tests.ps1 does, except don't create a VM. Must query what the template has created.

So now the question becomes how is this run on a VMSS instance?
```
Invoke-AzVMRunCommand -ResourceGroupName $VmResourceGroup -Name $VMname -CommandId 'RunPowerShellScript' -ScriptPath "$script:IncludeDir\..\Tests\TestImageVersion.ps1" -Parameter @{ImgName = $SkuName}
```

**Comment by robe070** [comment]
I've found it `Invoke-AzVmssVMRunCommand`

**Comment by robe070** [comment]
https://docs.microsoft.com/en-us/powershell/module/az.compute/invoke-azvmssvmruncommand?view=azps-4.4.0

**Comment by robe070** [comment]
```Powershell
Invoke-AzVmssVMRunCommand -ResourceGroupName 'rgname' -VMScaleSetName 'vmssname' -InstanceId '0' -CommandId 'RunPowerShellScript' -ScriptPath 'sample.ps1' -Parameter @{"arg1" = "var1";"arg2" = "var2"}
```

**Comment by ashutosh-kumar1** [comment]
Thanks for the inputs Rob.

**Comment by VarunChopraAccolite** [comment]
Hi @robe070 
The code is incorporated in the Azure Pipeline - Template Build Pipeline. Please review and let me know your comments for any further changes.

Thanks

**Comment by robe070** [comment]
I can see that the Template Build Pipeline tests it correctly.

I can see that the Image Release Pipeline has code to test it, but I've not found a job that has run the test. Please provide example of at least 1 image/template test thats NOT w12r2d142. Preferably a whole run. Whenever a template test is performed there should be a check to ensure the VMSS is using the expected image.

**Comment by VarunChopraAccolite** [comment]
hi @robe070 
The Image Release Pipeline [Release 36](https://dev.azure.com/VisualLansa/Lansa%20Azure%20Scalable%20License%20Images/_apps/hub/ms.vss-releaseManagement-web.cd-release-progress?releaseId=138&_a=release-pipeline-progress) covers 2012, 2016 images and [Release 37](https://dev.azure.com/VisualLansa/Lansa%20Azure%20Scalable%20License%20Images/_apps/hub/ms.vss-releaseManagement-web.cd-release-progress?_a=release-pipeline-progress&releaseId=139) covers 2019 images. Please find the SS of the same.
![image](https://user-images.githubusercontent.com/24430923/91649976-3d710600-ea97-11ea-97f1-8f291c6bf318.png)

Thanks
