### ISSUE TITLE
P2 Alter the Default LANSA MSI Depending on LANSA Version

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#49]
Alter the Default LANSA MSI Depending on LANSA Version

The default value used for the parameter `msiURL` must change based on which LANSA Version is chosen.

LANSA Version | msiURL
-- | --
V14 SP2 | https://lansalpcmsdn.blob.core.windows.net/app/test/AWAMAPP_v14.2.20715_en-us.msi
V15 GA | https://lansalpcmsdn.blob.core.windows.net/app/test/AWAMAPP_v15.0.0_en-us.msi

It would be ideal if this change to the default was in the template itself, and if thats not possible the behaviour may be implemented only in `createUIDefinition.json`. And the V15 GA url would be the default in the template.

Both `maintemplate.json` and `createUiDefinition.json` need this behaviour. It is for end users as well as developers.

A technique that may work in the template is to use a logic function to select the default value. And that may work in the `createUIDefinition.json` file too, otherwise hiding/showing copies of the same parameter may work, each with a different default.

**Comment by ashutosh-kumar1** [comment]
The changes are done and tested. PR raised for the same: https://github.com/lansa/azure-quickstart-templates/pull/6
