### ISSUE TITLE
P4 Provide backup of the Azure DevOps Pipeline configuration

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#52]

**Comment by VarunChopraAccolite** [comment]
Hi @robe070 
I had placed the Pipelines export in the source control. We can restore the Pipeline in the Azure DevOps by selecting the Import option. Please review and let me know your comments.
https://github.com/robe070/cookbooks/pull/69 

Thanks

**Comment by ashutosh-kumar1** [comment]
Hi @robe070, 
I have added a commit to update the JSON files with the latest pipeline export. Please merge: https://github.com/robe070/cookbooks/pull/69
