### ISSUE TITLE
P4 Document Pipeline usage

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#53]
Provide a summary of both the Image pipeline usage and the Template pipeline usage, in terms of what triggers what and the manual checks and interventions required.

**Comment by VarunChopraAccolite** [comment]
Hi @robe070 
Please review the [Lansa Pipelines: Usage Documentation](https://docs.google.com/document/d/1_OcxiP7YtCyktd_Gz79NupoFPTtW2pjpS5icTbE8aP8/edit#heading=h.x58cfto9e3yn) and let me know your comments.

Thanks

**Comment by VarunChopraAccolite** [comment]
hi @robe070 
I had completed the review comments. Please let me know if any further changes are required.

Thanks

**Comment by VarunChopraAccolite** [comment]
hi @robe070 
I had completed the review comments. Please let me know if any further changes are required.

Thanks
