### ISSUE TITLE
Azure Template: Support new Application Gateway Tiers and options

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#56]
Support the Application Gateway V2 tiers. Provide parameters similar to the default Portal Add AG blade as shown below:

![image](https://user-images.githubusercontent.com/4089160/91269923-3908cc80-e7bb-11ea-96e6-9852fdbd9856.png)

**Comment by robe070** [comment]
Note this documentation here https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2019-09-01/applicationgateways

And the possible values of SKU Name. What it does not say is that for V2 Tiers, the SKU Name is identical to the Tier. And that the4 SKU Names which start with 'Standard' are only valid for use when Tier = Standard, and WAF_Medium and WAF_Large SKUs are only valid when Tier = WAF. This logic may be gleaned form using the Portal interface as suggested in the first post above - 'Provide parameters similar to the portal'


| Name | Type | Required | Value |
| - | - | - | - |
name |  enum | No | Name of an application gateway SKU. - Standard_Small, Standard_Medium, Standard_Large, WAF_Medium, WAF_Large, Standard_v2, WAF_v2
tier | enum | No | Tier of an application gateway. - Standard, WAF, Standard_v2, WAF_v2
capacity | integer | No | Capacity (instance count) of an application gateway.

**Comment by robe070** [comment]
Also note the reference to 'and options' in the title. These settings are specific to choosing a V2 Tier:
![image](https://user-images.githubusercontent.com/4089160/98764075-25bae400-242f-11eb-880b-a235962fbf77.png)

The defaults should be the same as the Portal defaults - that is the same as in the image supplied.

All of these parameters need to be prompted for in the template.

**Comment by ashutosh-kumar1** [comment]
@robe070 , Need clarity regarding the Availability zone option.  I saw some examples containing the zones as an array of numeric string. Can you please specify the values w.r.t the dropdown? The other options can be implemented.
Adding example link: https://github.com/lansa/azure-quickstart-templates/blob/support/scalable/101-azurefirewall-create-with-zones/azuredeploy.json

**Comment by robe070** [comment]
It must behave like the portal https://portal.azure.com/#create/Microsoft.ApplicationGateway. That includes the hints.
Note the descriptions are Zone 1, Zone 2, Zone 3.
You will need to use a multi-select dropdown in the UI:
https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/microsoft-common-dropdown

It looks like there are either 3 Availability Zones or None. E.g. Australia Central is None and Australia East is 3.
And None is an option when there are 3 Zones.
In the template it should be implemented as an array with values none, 1, 2 and/or 3.

**Comment by robe070** [comment]
I would like to dynamically populate the Dropdown like the Portal does, but its not clear how to get a list of availability zones. This UI element would probably the one : Microsoft.Common.ArmApiControl or the Resource Selector.

**Comment by ashutosh-kumar1** [comment]
@robe070 , Please find attached the createUiDefinition file. The implementation of the zone would need to contain 'None' in the dropdown and would be the default value(could not find a way to not use a default value on load. Also the default value is expected to be from the list). The user will need to uncheck it and select the other zones if they want those zones to be considered.
Also, if 'None' is selected, the other selected zone will not be considered though it will be passed from the createUiDefinition file(This can be altered as per your expectation).

[createUiDefinitionfile.txt](https://github.com/robe070/cookbooks/files/5563175/createUiDefinitionfile.txt)

**Comment by robe070** [comment]
Can you not validate that if "0" is in the list then nothing else must be in it? You have implemented other validations previously.

Otherwise if, say, None and Zone 1 were selected, then "0", "1" are passed to the template. You will then check if the first value is "0" and if so the Availability Zones parameter will be set to empty, otherwise the whole value will we used?

I think it would be better if the template has no smarts. That the CreateUIDefinition passes an empty string if None is selected.

You know, I wonder if `None` is rendered by the Portal and its omission in the Sandbox is a limitation? Why don't you just leave the list as just the zones and lets publish it and see how it looks in preview? Make the field non-mandatory so it can be empty. It would be a shame to spend a heap of work for something that works out of the box.

**Comment by robe070** [comment]
The tooltips for the AG parameters need to be changed to be the same as the Portal. I've provided them here as some text change is required. I'll also send the text in an email so that you get the url markup, not as its rendered.:

**Tier**: The v2 tiers offer performance enhancements and support for some critical new features. Choose a WAF tier to support Web Application Firewall on this Application Gateway. You can upgrade to a WAF tier after the application gateway has been created. [Learn more about tier differences](https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-autoscaling-zone-redundant)

**Minimum Scale Units**: Additional reserved capacity which is always maintained irrespective of traffic. 0 signifies purely autoscaling Application Gateway with no additional reserved capacity while still maintaining high availability of the service.

**Availability Zone**: Some regions support the ability to put your v2 application gateway in an availability zone (or multiple, for zone redundancy). If you are not sure, create an Application Gateway in the Portal and see if Availability Zones are listed for your Region. [Learn more about Availability Zones](https://aka.ms/aboutaz)

**Comment by ashutosh-kumar1** [comment]
@robe070 , PR raised for the above-mentioned changes. The default value for 'label' and 'value' options of the field zone is set to ''(empty string). As observed default value is returned as String type and not array type. Also, for 'availabilityZone' field string type will not be accepted in the 'mainTemplate' as it is expecting an array and therefore the template validation will fail. 

Expecting it to work properly(the default value should also be an array of empty string) in Microsoft deployment. We at least need to give it a try. If it fails, we also might need to escalate this issue to the Microsoft team. We can discuss this if any further clarity is required.

Please test the createUiDefinition file and provide any further feedback. We can take it later if any enhancement is needed after verification with the Microsoft team.

**Comment by ashutosh-kumar1** [comment]
@robe070, The template release pipeline has executed successfully. Please proceed with the submission of the solution template.

**Comment by robe070** [comment]
Stackname validation seems to have been changed. No longer accepts numerics. Why is that?

**Comment by robe070** [comment]
The Peview Solution Template fails validation when default setting for Zones is used:
{"message":"Deployment template validation failed: 'Template parameter JToken type is not valid. Expected 'Array'. Actual 'String'. Please see https://aka.ms/resource-manager-parameter-files for usage details.'."}

**Comment by ashutosh-kumar1** [comment]
Thanks for this @robe070 . I was expecting this anyway and therefore am reiterating in every meeting that we might need to check this again.
Will have a look at this for a few hours and get back to you on this tomorrow.

**Comment by ashutosh-kumar1** [comment]
> Stackname validation seems to have been changed. No longer accepts numerics. Why is that?

This was updated based on your inputs Rob. It initially did accept numerals. Please refer issue #36 for details. Attaching screenshot for your reference.
![stackname validation](https://user-images.githubusercontent.com/67790012/100320916-e7edbc00-2fe7-11eb-95ac-81d52670dfa3.PNG)

**Comment by robe070** [comment]
> > Stackname validation seems to have been changed. No longer accepts numerics. Why is that?
> 
> This was updated based on your inputs Rob. It initially did accept numerals. Please refer issue #36 for details. Attaching screenshot for your reference.

Yes, indeed. Thanks for reminding me.

**Comment by ashutosh-kumar1** [comment]
@robe070 , New findings on this issue. I was able to use the if condition in the output with the restriction that we can not return an object or array. So I am planning to pass the array as a  string from the createUiDefinition file and then convert it back to an object in mainTemplate file. The mainTemplate file is able to use all the functions(object, array) properly but for some reason the createUiDefinition file is lacking this feature. Please provide your feedback.

**Comment by robe070** [comment]
Good to hear. Yes, do it.

**Comment by robe070** [comment]
What will the format of the string be that the template receives? - the template parameter `description` will need to describe the format.

**Comment by ashutosh-kumar1** [comment]
@robe070, PR raised to resolve the string conflict issue. Please review and merge: https://github.com/lansa/azure-quickstart-templates/pull/23

**Comment by ashutosh-kumar1** [comment]
Thanks @robe070 for merging the PR and running the template release pipeline even on weekend.

**Comment by robe070** [comment]
@ashutosh-kumar1 This behaviour does not seem to be what we discussed. 
New or Existing is not prompted for.
Where is the public ip address entered? 
We need to talk about this
![image](https://user-images.githubusercontent.com/4089160/100697136-40a6c580-33e9-11eb-88e1-d5378d886fb7.png)

**Comment by robe070** [comment]
Code complete only
