### ISSUE TITLE
P2 Remove WAF_V2 SKU from template

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#57]
This is incorrect. It has never been tested. So remove it for now. #56 will address the issue in the future.

**Comment by ashutosh-kumar1** [comment]
@robe070, Changes done and pull request raised for the same. Please review and merge : https://github.com/lansa/azure-quickstart-templates/pull/12

**Comment by ashutosh-kumar1** [comment]
@robe070, Let me know if any additional changes are required as a part of this issue or else please close it.
