### ISSUE TITLE
P3 Remove VM VHD when creating an image

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#58]
modify `bake-ide-ami.ps1` to delete the VHD before creating the VM so that repeat builds are always successful without requiring external deletions.

**Comment by VarunChopraAccolite** [comment]
Hi @robe070 
The code changes are in place. Please refer to the below commit and let me know your comments. Let me know if any further changes are required or we can close this one.
https://github.com/robe070/cookbooks/commit/e914925005a469f3d0c8e77524529b3bd8b764cc
