### ISSUE TITLE
Script to start a new VM to test updated Scalable License

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#6]
Ref: Baked Image Testing

1. All test scripts to be placed in .\tests
3. Create a PowerShell script to run a set of tests on an image. Name it .\tests\TestImage.ps1. This runs on a host machine to control the testing.
4. Prompt for image name. This is passed in from the script which bakes the image.
5. Prompt for Cloud provider name. This is passed in from the script which bakes the image.
6. Create the virtual machine using the image and wait for it to be ready. Example code for this is in the baking script. Code it with the expectation that it will be used with AWS too.
7. Now that the VM is ready, run the tests from the host on the VM in a similar manner to how the baking scripts were run to create the image.
8. Initially there will be just the one test to ensure the licenses are installed correctly. The script is in .\test\TestLicenses.ps1. It requires that $webuser is already created and is a local Administrator, so modify the script to implement that functionality.
9. The script indicates failure by throwing an exception. Catch the exception on the host and record a test failure. Otherwise record a success
10. More tests may be added in time.
11. This test script will be used in the pipeline constructed in Phase 3. Write it with this in mind.
12. All test output to be provided to the Architect for checking.

**Comment by ashutosh-kumar1** [comment]
Script pushed to branch with commit - 163204: Script to start a new VM to test updated Scalable License. The finally blocks deletes the VM post the test execution.
@robe070 Please review the code.

**Comment by ashutosh-kumar1** [comment]
@robe070, Please find attached execution log

[log for issue #6.txt](https://github.com/robe070/cookbooks/files/4986697/log.for.issue.6.txt)
