### ISSUE TITLE
Chocolatey download and install failures

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#60]
### Defect
It is quite common to have Chocolatey download and install failures. So a solution is required to remove this failure from the AWS and Azure CI pipeline.

### Azure DevOps Artifact Solution (Preferred)
Investigate the potential of using an Azure DevOps Artifact nuget upstream package manager to cache installs that are currently obtained from Chocolatey. Can these be accessed from the VM that is being baked?

### BLOB solution
As part of bake-ide-msi.ps1 processing wherever choco is called, which is at least in `install-lansa-base.ps1`, wrapper `Run-ExitCode 'choco'...` 

Check on Choco what the latest version is thats available, and if its changed download it and upload that to BLOB storage. If its not changed, just download and install from BLOB. Though I've seen AWS BLOB fail too when you are not in the same Region. Possibly Azure is better at that.

Will require design of knowing what the current version is. Is BLOB sufficient? Maybe the file currentversion.txt in the folder kdiff3 is downloaded first. Check if a later version is on choco, etc.

**Comment by robe070** [comment]
I cannot see a way to have an upstream source in an Artifact Feed. Documentation shows it, but its not there in the current interface, that I can see.

So, lets move ahead with manually uploading the current Chocolatey packages, which I will do, and then modify the Image build scripts to access the `choco` Azure DevOps Artifacts Feed instead of the public Chocolatey feed.

This link describes my research: https://www.evernote.com/l/AA1AW2DOWSBPsqM0FxoMvJLF7Hvn7fO5X8A/
Notice that the link in the header is to a set of detailed instructions which the Research presumes has been read. Also note that that link is based on a non-current version of Azure DevOps, so some example pages are not correct.

```
choco source add -n=choco `
-s="https://pkgs.dev.azure.com/VisualLansa/_packaging/choco/nuget/v2" `
-u="AzureDevOpsArtifacts@lansacloudlansacom.onmicrosoft.com" -p="ln65igsabq56drqml3vvcyxcldhdzdjcnvvqjvtuvoj34q4egllq"

then to install a package:
choco install <an install package> -s choco
```

Firstly, adding the chocolatey source `choco` must be done in the script `getchoco.ps1`.
Then modify `installGit.ps1` to specify `-s choco` on the choco command line calls.
When thats working...
Modify the main script `lansa-install-base.ps1` to specify `-s choco`

N.B. The PAT will be checked in to the git repo and that is OK because it only has rights to read the packages and nothing else.

N.B.B. Dev test: manually run the image build, put a pause in the script after the installs have been done and then RDP in. This will allow you to quickly prove that the applications have been installed correctly.
N.B.B.B. Unit Test: Repeat the test from the Image thats built

Its expected that the above scripts will be searched for choco installs and all of them modified to use the AzureDevOps Artifacts Feed using the parameters `-s choco`.

This is a minimum list of installs that will need to be checked by RDP and running the application:
Google Chrome
kdiff3
FoxitReader
VS Code

Note that jre8 is tested by the url tests.
And git is tested automatically because its fundamental to building an image successfully.

**Comment by robe070** [comment]
All packages have been uploaded to the Azure DevOps Artifacts Feed called `choco`.

Coding may be fully completed.

**Comment by robe070** [comment]
@ravicharan07 Make sure the Azure image CI pipeline passes. Post success here. And I'll close this issue.

**Comment by ravicharan07** [comment]
@robe070 CI pipeline job completed successful. please refer build #[396   ](https://dev.azure.com/VisualLansa/Lansa%20Azure%20Scalable%20License%20Images/_build?definitionId=12)

**Comment by robe070** [comment]
@VarunChopraAccolite The Azure Image builds, both CI and Image Release Artefacts are failing due to security, runs #488 and #501. Prior ones are failing for other reasons.

What changes have been made? Maybe somebody changed the user that the builds are being performed under?

Maybe something to do with a Service Connection being changed?

**Comment by robe070** [comment]
I tried directly accessing the Azure Artefacts form my PC. It failed with the same errors. Somehow the PAT has become invalid. I wonder if one of your team who is using the AzureDevOpsArtefacts user has regenerated the PAT? That seems to be the only way for this to have occurred. Expiry is 12th November 2021.

New PAT is 266tdaklo47lhxfvaz7pgqagpyz72uoeahjyg7mkpaxtwdzmkp6a. This is already in the public domain. It only has read access to the Artefacts.

Please update in the pipeline ASAP!

**Comment by VarunChopraAccolite** [comment]
Hi @robe070 
I will check with the team and history for any modifications. I will update the PAT.

**Comment by VarunChopraAccolite** [comment]
cc: @ravicharan07 you have to modify the PAT in the choco to make sure it works as discussed above
