### ISSUE TITLE
Increase Application VMSS maximum capacity to 600 instances

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#61]
The capacity of the application VMSS is currently capped at 100 instances as that was once the Azure recommendation. It has now increased to 600.

Also need to increase the UI and template Maximum Instance Count constraint to MAX 600.

**Comment by ashutosh-kumar1** [comment]
PR raised for this issue: https://github.com/lansa/azure-quickstart-templates/pull/17.
@robe070 The issue can now be closed as the PR is merged.
