### ISSUE TITLE
Test Image Using the stack **Before** Submission to AMP 

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#7]
Ref: Testing Image and Template **Before** Submission to AMP 
Part of Deliverable: Script to start up a stack and test that the application functions properly when deployed locally and through Azure Marketplace when in preview

1. Create a PowerShell script to test that the image may be used by the template.
3. The template being used for Phase 1 will be the Azure Quickstart template.
4. For subsequent phases it will be the Solution Template in the LANSA git repository. Of course, the Solution Template will start off with the Azure Quickstart template source code so changes made to the Azure Quickstart Template will be inherited by the Solution Template.
5. Construct a script to create and test a stack using the new image. This also requires modifying the template to be able to choose to select the new image rather than using a Marketplace image. And ensure it passes successfully. The template change will not be submitted to Azure Quickstart templates nor to Azure Marketplace as a Solution Template, though the changes will be incorporated into Phase 2.
6. These urls are given from the perspective of executing inside the Windows instance. Localhost must be changed to the public ip address. The public ip address will need to be derived from the template output. These tests will also be used in Testing Preview Template or Preview Image.
7. http://localhost/80/cgi-bin/probe returns 200 - SYSTEM READY
8. http://localhost/cgi-bin/lansaweb?about returns 200
9. http://localhost/cgi-bin/lansaweb?wam=DEPTABWA&webrtn=BuildFirst&ml=LANSA:XHTML&part=DEX&lang=ENG returns 200
11. http://localhost/cgi-bin/lansaweb?wam=JSMLICE&webrtn=weblic&ml=LANSA:XHTML&part=DEX&lang=ENG returns 200. (500 indicates an Integrator license error)
10. If the public ip address times out, its likely the Application Gateway SSL certificate has expired. So, to obviate this occurring, the test harness should create a new self-signed certificate each time it runs, and remove the certificate at the end of the test.  Code for creating a self-signed certificate may be found here: .scripts\GenerateSelfSignedCertificate.ps1
11. Extensive testing of the application is not required. Its purpose is to test that LANSA will run in the image.
12. All test output to be provided to the Architect for checking.

**Comment by ashutosh-kumar1** [comment]
@robe070, Do we need to deploy azure stack separately and then connect to azure stack with the help of PowerShell script for testing the image or is there any other way for testing the stack? Meanwhile, I am proceeding with modifying the template and the parameters to create the resources.

**Comment by robe070** [comment]
You need to execute web requests using PowerShell against the `lbfqdn` output value. This the the  Fully Qualified Domain Name of the web server. That value needs to be inserted instead of `localhost` in the urls provided in the first comment.

You can find similar code in this script `.\GitHub\cookbooks\CloudFormationWindows\CheckVLWebStatus.ps1`. This script searches for LANSA stacks that are named a certain way. Thats not what you are doing as you already have the stack url. Just look at the `Invoke-WebRequest` handling.

**Comment by robe070** [comment]
@VarunChopraAccolite @ashutosh-kumar1 
Given the closeness to completing Phase 1 and the possibility raised yesterday by Varun that testing within the pipeline may not use PowerShell, I think you should postpone the completion of the script until Phase 2.

For now, with the modified template, create a LANSA stack using the new image `w12r2d-14-2-10image` and manually run the 4 tests. Use the deployment script with `test.parameters.json`.
With the results of those tests I can close this issue and proceed with publishing of the image.

I can duplicate this issue for Phase 2 and amend as necessary.

**Comment by VarunChopraAccolite** [comment]
Hi @robe070 
Sure, we will test and post the results for your review.

**Comment by ashutosh-kumar1** [comment]
I have created a resource group, vmss and a database with name rgak, vmssak and test-ak respectively. We are getting an error while executing the file Deploy-AzureResourceGroup.ps1 with the updated test parameters. Attaching error log for reference [error issue #7.txt](https://github.com/robe070/cookbooks/files/4995260/error.issue.7.txt) .
@robe070 Can you please review the attached file and provide us feedback while we are looking into the issue?

**Comment by robe070** [comment]
Well the parameters look correct. Except that I cannot check the passwords because you haven't supplied the parameter file. And all I can check is if they are complex enough. Thats just about the only reason this deployment would fail. Apart from you supplying the incorrect database user and password.

You've also run the deployment script using the default parameter file. You were [instructed to use test.parameters.json](https://www.evernote.com/l/AA2k2Nqi6UtA4YYx0k4_NIoyG8v8fLurcec/). Like this:
`.\Deploy-AzureResourceGroup.ps1 'Australia East' 'script' -TemplateParameterFile '.\test.parameters.json'`
Its fine to use you're own one, but I had setup `test.parameters.json` so that it would avoid common password issues.

I note that you've created a database server for your self. There is no need for that. You can just create a database in the testsrv-dp database server. Much quicker. And you've created the database with the correct parameters. Thank you for that. I've update the [database setup note](https://www.evernote.com/l/AA2yqmzpa_lMe4apelBemQccuTB7lOa8E7o/) to make it clearer.

**Comment by ashutosh-kumar1** [comment]
Hi @robe070 ,
Post the execution of StopStartAppGW job, I am able to access the output lbFqdn : https://agvmssak.australiaeast.cloudapp.azure.com from my browser. Still, when I am trying to access the URLs provided in the issue description, I am getting a status of 4001 and not 200.

**Comment by robe070** [comment]
They work for me. Here is 1 example:
![image](https://user-images.githubusercontent.com/4089160/88901302-fc1ce900-d293-11ea-9d24-0c74f9cf7807.png)

**Comment by robe070** [comment]
And the other complex one:
![image](https://user-images.githubusercontent.com/4089160/88901479-2d95b480-d294-11ea-9c30-82d37c8383cc.png)

**Comment by ashutosh-kumar1** [comment]
Any additional thing that needs to be done @robe070 ?
When I am executing the same it is showing me a blank page with 4001 code. Any privileges required?
Any setup required for 'https://agvmssak.australiaeast.cloudapp.azure.com'?
![code 4001](https://user-images.githubusercontent.com/67790012/88902548-ff05e280-d26f-11ea-8ae1-bf49d512a06b.PNG)

**Comment by robe070** [comment]
You've not typed the colon:
https:

**Comment by robe070** [comment]
I've tried to email you on ashutosh.kumar1@accoliteindia.com and it rejects saying this address does not exist:
Notice the different address its been **converted** to
![image](https://user-images.githubusercontent.com/4089160/88909628-b44f8f00-d29e-11ea-93be-5b8795787d44.png)

If you still have an issue, call me on +61404093890 as I may not be looking at my email.

**Comment by ashutosh-kumar1** [comment]
Thanks @robe070 for looking into the issue. I think it is some issue/blockers with chrome on my local system which did not allow the URL to execute properly and converted the URL to 'https//agvmssak.australiaeast.cloudapp.azure.com/cgi-bin/probe'. 
Changing the browser to IE worked.

**Comment by ashutosh-kumar1** [comment]
@robe070 I have pushed the code changes of azuredeploy.json file to my repo 'https://github.com/ashutosh-kumar1/azure-quickstart-templates' with commit '163204 Hardcoding Image ID to use custom image for deploying stack'. Do I need to make changes anywhere and commit for this issue? 

Output String obtained as below:
OutputsString           :
                          Name             Type                       Value
                          ===============  =========================  ==========
                          dbServerName     String                     testsrv-dp.database.windows.net
                          dbName           String                     test-ak
                          lbFqdn           String                     https://agvmssak.australiaeast.cloudapp.azure.com
                          dbrdpAddress     String                     dbvmssak.australiaeast.cloudapp.azure.com:50000
                          rdpAddress       String                     vmssak.australiaeast.cloudapp.azure.com:50000

Testing was done manually with the latest image. I will update the image URI details in issue #8

**Comment by robe070** [comment]
@ashutosh-kumar1 
> Do I need to make changes anywhere and commit for this issue?

No you do not. The code will need to be incorporated into the changes made to the template as part of Phase 2
