### ISSUE TITLE
Image Build pipeline often fails to build all 6 images due to VM provisioning error of test VM

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#72]
If all 6 images are built at the same time, some will fail to be properly created and thus the VM created as part of the test fails to provision.

So what kind of serialisation can we enforce on the creation of the images. Just the part that takes the generalised VM and creates an image from it.

One work around might be to duplicate the Image Build pipeline and build 3 and 3 with, say, 10 min delay between each job. Then would also need to duplicate the Release pipeline so those parameters could be baked in. Now changes may be required to the pipelines, so for the moment keep it as it is.

Workaround is to delete the failing resource groups when they are taking too long to create the test VM. And then rerun failed jobs.

And so I ran some tests and it worked flawlessly! The first run in the table below is the one that raised this issue:

Job # | Jobs Started | Successes | Fails | Time
-- | -- | -- | -- | --
239 | 6 | 3 | 3 | 3:24 pm AEST
240 | 4 | 4 | 0
241 | 4 | 4 | 0
242 | 4 | 4 | 0
243 | 5 | 5 | 0
244 | 5 | 5 | 0
245 | 6 | 6 | 0 | 8 pm AEST ?
246 | 6 | 1 | 5 | 9 am AEST

Its like its a resourcing issue. Does not seem to be time of day related.

**Comment by robe070** [comment]
A dialog has occurred with Azure Support who have suggested the following in the attachment. Investigate their recommendations and report back:
[Sysprep Email.pdf](https://github.com/robe070/cookbooks/files/5290732/Sysprep.Email.pdf)

**Comment by robe070** [comment]
The way to work with these issues efficiently is to put a messagebox in bake-ide-ami.ps1 just before you want to modify the code. Then RDP into the VM and run your Powershell directly so you can work through issues. Much the quickest way.

Also, if this solution works it should also be an issue for AWS. So ultimately, once the fix is working, the condition on Azure should be removed.

**Comment by robe070** [comment]
Run #722 started at about 1 pm on a Saturday had 0 failures due to failed sysprep. There was 1 failure and that was an issue with vscode install.
```
2020-12-12T02:38:21.1262374Z Failures
2020-12-12T02:38:21.1265679Z  - vscode (exited 1) - vscode not installed. An error occurred during installation:
2020-12-12T02:38:21.1268918Z  The remote name could not be resolved: '4r5vsblobprodeau131.blob.core.windows.net'
```
![image](https://user-images.githubusercontent.com/4089160/101971613-d57dae80-3c86-11eb-9a02-f150a90d443a.png)

And the failed build, was successful when failed jobs were restarted.

**Comment by VarunChopraAccolite** [comment]
Hi @robe070 
It might be an intermittent package issue, AFAIK. Let me know your thoughts.

**Comment by robe070** [comment]
Yes, indeed and I'm not concerned about it. We cannot remove the dependency on the location of the components of the packages. All we have done is remove the dependency on the Chocolatey server. And that seems to be working better.

I only mentioned it to record the success of running the 6 builds concurrently on the weekend and to note the failure is not due to the usual reason.

So FYI only.

**Comment by robe070** [comment]
Implemented MS recommendations to delete the unattend.xml and wait for VM to completely shutdown before terminating it.
Ran the test 5 times and it was successful each time, but this does not necessarily prove its fixed. Of the 2 fixes, waiting for a complete shutdown is the only one that explains the symptoms seen - its random/a timing issue. And the logs show that the first execution on the VM fails every single time, that is, its completely shutdown. Now there is a sleep of 5s before this is attemped, so that MAY be fixing it, but that seems too quick to be making a difference. Whats more likely is that on the 13th January in Australia the load on Azure is low - duplicating the weekend scenario when it always worked previously. So a full test will only be possible once the holidays are finished in early February.

Also implemented for AWS. Firstly just part (2) the proper shutdown. The VM still failed to shutdown in 1 out of 3 cases. So, implemented part (1) as well - thats now running.

**Comment by robe070** [comment]
There have been maybe 4 build on AWS during business hours. All have built all images successfully. Though some images fail the sysprep and are automatically re-attempted and eventually succeed. Up to 3 attempts has been seen.

Azure has had fewer builds, and all successful first time, no retries required.

So closing this issue for now.
