### ISSUE TITLE
Post: Image Release pipeline using incorrect branch for Preview tests

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#73]
As per the Wiki - DevOps branching - and now added to the documentation, Preview test need to be run on the patch/paas branch.

Note that Integration test uses debug/paas, which is correct
Note that Production test uses the default branch - support/scalable - which is correct

**Comment by ashutosh-kumar1** [comment]
@robe070, Preview test branch for image release pipeline updated to patch/paas.
Also raised a PR for updating the pipeline backup in cookbooks repo: https://github.com/robe070/cookbooks/pull/75. Please verify and merge the PR.
