### ISSUE TITLE
Integrate Azure Key Vault into v2 Application Gateway 

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#76]
Integrate Application Gateway with Azure Key Vault to store, retrieve and renew certificates.

Requirements:
1. Key Vault must have parameter -enabled-for-template-deployment set to true. 
2. The Key Vault is created and managed external to the LANSA template
2. The SSL Certificate will be a Key Vault Certificate.
3. The SSL Certificate password will be a Key Vault Secret.
4. It is expected that the SSL Certificate is to be configured for automatic renewal in Key Vault. And it may be manually renewed in Key Vault. Whichever mechanism is used, no manual intervention must be required for the LANSA stack to continue operation uninterrupted.
5. Certificate and Password must be dynamically generated upon renewal.
6. The Key Vault must be in the same subscription as the Application Gateway.
7. The current parameters `certificateBase64Encoded `and `certificatePassword` will be replaced by the Key Vault Certificate identifiers and the Key Vault Secret identifiers.

**Comment by ajitesh-s** [comment]
Hi @robe070 I have updated the PR with recent changes. How do we need to test that which cert (the existing one or the one from key vault) is being used in the arm template. I have tested this by outputting the parameter value that is referencing the cert and comparing the outputted strings for cases when keyVaultEnabledForTemplateDeployment parameter is set to true and false respectively. 
I am getting different strings in both cases.

**Comment by robe070** [comment]
Hi @ajitesh-s 
How did you go? Did you get anywhere with my suggestions? I would have thought you could have worked through them easily in the time you had left in your day. So is it now working?

**Comment by robe070** [comment]
Code complete only

**Comment by ashutosh-kumar1** [comment]
@robe070, the scenario for using the key vault certificate is added in the regression pipeline (Refer: Test Stack).

**Comment by robe070** [comment]
@ajitesh-s @ashutosh-kumar1 
We have received the following feedback from Azure MP
![image](https://user-images.githubusercontent.com/4089160/104267150-2e8a6d80-54e5-11eb-9812-7cacf98e9120.png)

And I wonder myself about the previous nested template that seems to do nothing, and may in fact be what the reviewer is referring to?
![image](https://user-images.githubusercontent.com/4089160/104267315-7a3d1700-54e5-11eb-924a-875266a4bab9.png)

**Comment by robe070** [comment]
@ajitesh-s 
@ashutosh-kumar1 
Can you explain to me how the Azure Release pipeline `Issue Resolution Template Release` which is archived, has become the Release pipeline for the Azure `Templates - Azure Quick Start CI` pipeline. This has been changed since I last released the template.

**Comment by ashutosh-kumar1** [comment]
It is very weird to hear this behavior @robe070, as I do not remember any further changes made in Azure pipelines. The last run was made in Template Release post delivering all the azure issues. Then and there we froze the Azure issues and pipeline related work.

**Comment by robe070** [comment]
This Issue has been completed except for the following issue raised above:
> Can you explain to me how the Azure Release pipeline `Issue Resolution Template Release` which is archived, has become the Release pipeline for the Azure `Templates - Azure Quick Start CI` pipeline. This has been changed since I last released the template.

So, make the Azure `Template Release` pipeline the default release pipeline for the Azure `Templates - Azure Quick Start CI` pipeline.

**Comment by ashutosh-kumar1** [comment]
@robe070 , We can look into this issue. On trying to access the account it says 'the account is locked'! Can you provide me the access?
Username: ashutoshkumar@lansacloudlansacom.onmicrosoft.com

**Comment by robe070** [comment]
@ashutosh-kumar1 
I've given you access

**Comment by ashutosh-kumar1** [comment]
@robe070, I have fixed the default selection for the release stage. FYI, the drop down displays all the pipeline names in the list sorted in alphabetical order so it was picking the `Issue Resolution Template Release` branch by default (which was the first entry). I changed the name to `Template Release Issue Resolution` and things went back to the desired state.

You can revert back the changes of the default version in the Template Release pipeline if it is desired.

Additionally, I have created a PR https://github.com/lansa/azure-quickstart-templates/pull/28 to fix the API version and json error that was breaking the ARM TTK cases in the template CI pipeline. The CI pipeline executes properly now. Please review and merge.
Please let me know if any issue still exists or you can close the issue.
