### ISSUE TITLE
Publish CloudFormation Template using current Win Server 2012 image

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#78]
Ref: [AMI-based delivery using AWS CloudFormation](https://docs.aws.amazon.com/marketplace/latest/userguide/cloudformation.html) ...and note the need to use the [template testing tool](https://github.com/aws-quickstart/taskcat)

Take the existing [LANSA CloudFormation template]( https://raw.githubusercontent.com/robe070/cookbooks/debug/paas/CloudFormationWindows/lansa-win-custom.cfn.template)
...and alter its structure to use nested templates in the same manner as the initial LANSA Stack did before it was restructured into a single template to conform to AWS Marketplace restrictions. The initial templates are [here ](https://raw.githubusercontent.com/robe070/cookbooks/debug/paas/CloudFormationWindows/lansa-master-win.cfn.template) and [here](https://raw.githubusercontent.com/robe070/cookbooks/debug/paas/CloudFormationWindows/webserver-win.cfn.template)

As the current template came from the combined initial nested templates, almost all the code is the same. It should be relatively easy to peel the current template apart into nested templates.

Also move the templates into a new public github repo lansa/aws-templates. This is critical so that a CI pipeline may be triggered on PR open.

The custom template already contains AMI ID references to the existing Windows Server 2012 images and thus new images are not required to be built, accepting that an email has been received from AWS saying that the Windows Server 2012 images need to be updated. So they may not accept the current images. It may require that the Image pipeline is in operation before the Template may be published with the newly built image.

**Comment by robe070** [comment]
Note that the base image id for AWS is `w12r2d-14-2` (Azure was `lansa-scalable-license-14-2`). All other base Image Ids are the same on AWS as for Azure. This effects the AWS Image and AWS template CI and CD pipeline parameters too.

**Comment by nikpok** [comment]
Hi @robe070 
Facing the server IP address not found issue for -https://775488040364.signin.aws.amazon.com/console
Also the nested template timed out on WaitCondition for both the server group in stack 78.
The templates are uploaded in the s3 debug/paas.
Following is the commit link.
[https://github.com/VarunChopraAccolite/aws-templates/commit/b35b8507bb8bc47036bb53dcbe22b1c6543d9cf5#diff-058e2ba4b27421a0c2ae2af5ab2f7b5d726290d350b9d1a4dd61e4fb50c76068R6](url)
We are trying to figure out same,pls let us know your inputs.
Thanks

**Comment by robe070** [comment]
What server ip address not found? That link is fine.

I've cloned this repo to look at the changes more closely

**Comment by nikpok** [comment]
Hi @robe070 
The server issue has been resolved as it was a DNS issue.
We have tried following two ways and both of them resulted in successful stack creation.
1-By placing the AWS.EC2.Windows.CloudWatch.json in the debug/pass folder location.
2-By removing the below mentioned code from the webserver template.
   `"files"    : {
                            "c:\\program files\\Amazon\\Ec2ConfigService\\Settings\\AWS.EC2.Windows.CloudWatch.json" : {
                               "source" : { "Fn::If" : [ "IsReleaseLevel", 
                                              { "Fn::Join" : ["", [
                                                       { "Ref" : "TemplateRoot" },
                                                       { "Ref" : "10LansaGitRepoBranch" },
                                                       "/AWS.EC2.Windows.CloudWatch.json"
                                              ]]},
                                              { "Fn::Join" : ["", [
                                                       { "Ref" : "TemplateRoot" },
                                                       { "Ref" : "10LansaGitRepoBranch" },
                                                       "/beta/AWS.EC2.Windows.CloudWatch.json"
                                              ]]}
                                           ]}
                            }
                         },`
In both cases we have successful stack creation. Providing here the stack details:
For case 1:
https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stacks/stackinfo?stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-2%3A775488040364%3Astack%2FLatest-Stack-78%2F6d2e1f10-3496-11eb-ba80-060eeed191fe
For case 2:
https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stacks/stackinfo?stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-2%3A775488040364%3Astack%2Flansa-stack-watch-log-78%2F92f4c770-349c-11eb-938a-02d8953651cc
Please provide your inputs for further testing the correctness of the templates
Thanks

**Comment by robe070** [comment]
@VarunChopraAccolite Please ensure all developers who need to test the template know this change is required.

1. Incorrect. As I said in Slack its old code that needs to be removed!
2. Correct, and application is working

I've deleted stack (1). I've left stack (2) for me to check the cloud watch logs are working.

In order to test the stack correctly I needed to make a small change in the parameters. This will be the cause of "2 urls not working" reported in the review meeting.

But the fix is not to apply that change. Instead I have uploaded the same application used in Azure to AWS.

This means that the default MSI in the templates (Custom and Master) needs to be changed from
`"https://s3-ap-southeast-2.amazonaws.com/lansa/app/Test/AWAMAPP_v14.2.1_en-us.msi"`
to
`"https://s3-ap-southeast-2.amazonaws.com/lansa/app/Test/AWAMAPP_v14.2.20715_en-us.msi"`

And the 15.0 tests in the pipeline need to refer to this MSI:
`"https://s3-ap-southeast-2.amazonaws.com/lansa/app/Test/AWAMAPP_v15.0.0_en-us.msi"`

**Comment by VarunChopraAccolite** [comment]
Hi @robe070 
We will modify it as part of this issue, thank you for your inputs.
cc: @nikpok raise a PR including the default MSI changes

**Comment by robe070** [comment]
Just to be clear, the pipeline I'm talking about is AWS, NOT Azure. Azure MSI links stay as they are.

**Comment by nikpok** [comment]
Hi @robe070 
We have made the changes for the default MSI as well.
Also all the tests have passed with status 200 OK.
Corresponding PR link:https://github.com/lansa/aws-templates/pull/4
Please have a look and let us know your thoughts.
Thanks and Regards
Nikhil

**Comment by robe070** [comment]
So is there an archive to provide to AWS Marketplace?

**Comment by robe070** [comment]
CI pipeline should provide it.

**Comment by srinivasp898** [comment]
Added archive file task for CI pipeline.
please find below successful build
[https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_build/results?buildId=790&view=logs&j=cfa20e98-6997-523c-4233-f0a7302c929f&t=cfa20e98-6997-523c-4233-f0a7302c929f](url)
