### ISSUE TITLE
AWS template: Package up settings into ‘Shoe Sizes’

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#79]
Simplify template parameters into fixed sets of parameters for small, medium and enterprise stacks. Plus a custom set of parameters to allow all parameters to be modified, as now.

Also include dev & test options.

This may be implemented using parent nested template(s) to call the existing custom template. 
	* Publish 5 separate shoe-size parent templates which call a url in S3 for the main template and other nested templates

This is necessary because there are no conditional parameters - parameters which hide the display of other parameters.

Details of the UI needs to be determined.

**Comment by knagasekharreddy** [comment]
@robe070 can you add more details about the `shoe sizes` i am working on this issue.

**Comment by robe070** [comment]
@VarunChopraAccolite  @srinivasp898 It won't be soon. Firstly Issue #78 needs to be completed.

**Comment by robe070** [comment]
Essential Parameters Parameter Group

Show all parameters with defaults, except hide the MSI Bitness as shown below:

![image](https://user-images.githubusercontent.com/4089160/101122991-e0618f00-3647-11eb-8cc5-50134ce1171e.png)


Database Configuration
Parameter | Hide | Development | Test | Small | Medium | Large
-- | -- | -- | -- | -- | -- | --
Instance Class | yes | db.t3.small | db.t3.large | db.t3.2xlarge | db.r5.xlarge | db.r5.8xlarge
Name | yes | lansa | lansa | lansa | lansa | lansa
SQL Server Engine Type | yes | sqlserver-web | sqlserver-web | sqlserver-web | sqlserver-se | sqlserver-ee
Maximum Size (GB) | yes | 100 | 100 | 500 | 1000 | 1000
IO Ops | yes | 1000 | 1000 | 5000 | 10000 | 10000


Web Server Configuration
Parameter | Hide | Development | Test | Small | Medium | Large
-- | -- | -- | -- | -- | -- | --
OS Version | No | default | default | default | default | default
LANSA Version | No | default | default | default | default | default
Instance Type | Yes | t3.micro | t3.medium | t3.medium | t3.2xlarge | r5.large
Maximum Web Jobs | Yes | 10 | 20 | 20 | 60 | 120
Minimum number of instances | Yes | default | default | default | default | default


Stack Maintenance
Parameter | Hide | Development | Test | Small | Medium | Large
-- | -- | -- | -- | -- | -- | --
Trigger Cake Update | Yes | default | default | default | default | default
Trigger Chef Update | Yes | default | default | default | default | default
Trigger Win Update | Yes | default | default | default | default | default
Trigger Web Config | No | default | default | default | default | default
Trigger Icing Update | No | default | default | default | default | default
Trigger Patch Install | No | default | default | default | default | default
Patch Bucket Name | No | default | default | default | default | default
Patch Folder Name | No | default | default | default | default | default


Advanced Configuration
(All are hidden so there is no Advanced Configuration parameter group shown)
Parameter | Hide | Development | Test | Small | Medium | Large
-- | -- | -- | -- | -- | -- | --
Load Balancer Timeout | Yes | default | default | default | default | default
User Script Hook | Yes | default | default | default | default | default
Git Repository Branch | Yes | default | default | default | default | default

These 5 shoe Sizes must be added to the Regression Test Suite in the AWS Template Release pipeline.

**Comment by robe070** [comment]
Parameters must be removed from the Shoe Size templates if they are hidden and do not change the default value. Its important that the Master template default values are used where possible so as to minimise changes in the future.

**Comment by SakshamAccolite** [comment]
Hi @robe070 ,
Could you please confirm, out of the new parameters (LansaVersion, ImageSource, AMIId, CreateVPC, CurrentVPC, AvailabilityZones, NumberOfAZs, DBSubnetGroupName, ELBSubnetIds) which all I need to add in ShoeSize templates and which all need to be hidden.

**Comment by robe070** [comment]
LansaVersion, Show and pass on.
ImageSource, Hide, do not pass on.
AMIId, Hide, do not pass on.

CreateVPC, CurrentVPC, AvailabilityZones, NumberOfAZs, DBSubnetGroupName, ELBSubnetIds all of these shown, prompted and grouped and passed on as per Master template.

**Comment by SakshamAccolite** [comment]
Hi @robe070, 
As the changes have been merged successfully, are we good to close the issue?
