### ISSUE TITLE
Build & test windows Server 2012, 2016, and 2019 images for v14.2 and v15

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#80]
Copy and then modify the existing Azure LANSA Images on-demand CI pipeline to construct & test all the AWS images.

The template will also require modifying to add Windows 2019 to the possible choices. The key to this change is adding to the mapping `AWSRegionArch2AMI`.

**Comment by robe070** [comment]
-AmazonAMIName 
The 2012 image uses: "Windows_Server-2012-R2_RTM-English-64Bit-SQL_2016_SP2_Express*"
The 2016 image uses: "Windows_Server-2016-English-Full-SQL_2017_Express*"
The 2019 image uses: "Windows_Server-2019-English-Full-SQL_2019_Express*"

**Comment by robe070** [comment]
Note that the base image id for AWS is `w12r2d-14-2` (Azure was `lansa-scalable-license-14-2`). All other base Image Ids are the same on AWS as for Azure. This effects the AWS Image and AWS template CI and CD pipeline parameters too.

**Comment by robe070** [comment]
@ravicharan07 You will need changes from praveen, after they've been fixed to pass in personalised parameters.
@praveen-acc @ashutosh-kumar1

**Comment by robe070** [comment]
@VarunChopraAccolite I'd like to point out that this issue describes the need to update the template to support Windows 2019 and the already supported 2016 which the master template supports in the following table, but which was removed as an option from the `11WebserverOSVersion` parameter. And there is the implied need to support the 2 LANSA versions to match up with Azure.

This is the current mapping:
```json
      "AWSRegionArch2AMI": {
         "Metadata": { "Comment1": "This mapping is updated whenever a new AMI is submitted to Marketplace" },
         "us-east-1": { "win2012": "ami-0e595def70f14bbe4", "win2016" : "" },
         "us-east-2": { "win2012": "ami-058af61789274bb95", "win2016" : "" },
         "us-west-1": { "win2012": "ami-097ce131f533d28ed", "win2016" : "" },
         "us-west-2": { "win2012": "ami-069f525710ebdd472", "win2016" : "" },
         "ca-central-1": { "win2012": "ami-04d7f1932b8d66bfd", "win2016" : "" },
         "eu-central-1": { "win2012": "ami-082bfe59e157a402e", "win2016" : "" },
         "eu-west-1": { "win2012": "ami-0b752c2d057fb001a", "win2016" : "" },
         "eu-west-2": { "win2012": "ami-00a8a2f24f010c624", "win2016" : "" },
         "eu-west-3": { "win2012": "ami-0c6066ea9e07aeaa2", "win2016" : "" },
         "eu-north-1": { "win2012": "ami-d270f9ac", "win2016" : "" },
         "eu-south-1": { "win2012": "", "win2016" : "" },         
         "ap-southeast-1": { "win2012": "ami-0a606cfbd7dc17e53", "win2016" : "" },
         "ap-southeast-2": { "win2012": "ami-09509d8e30a702bc6", "win2016" : "ami-063c84b9992a58aea" },
         "ap-south-1": { "win2012": "ami-0e1a7a4677a06a03f", "win2016" : "" },
         "ap-northeast-1": { "win2012": "ami-01debc7e21503586d", "win2016" : "" },
         "ap-northeast-2": { "win2012": "ami-00fda912916e5aa4e", "win2016" : "" },
         "ap-east-1": { "win2012": "", "win2016" : "" },
         "af-south-1": { "win2012": "", "win2016" : "" },
         "me-south-1": { "win2012": "", "win2016" : "" },         
         "sa-east-1": { "win2012": "ami-0531a6656fd4cf471", "win2016" : "" }
   }
```

This construct only allows for 2 levels - in this case region and OS. There is no provision for a third element.

So the mapping will need to be duplicated.

The current mapping will need to be renamed to `AWSRegionArch2AMI14-2`.
And a new one created called `AWSRegionArch2AMI15-0`.

To support the LANSA versions a parameter needs to be added: 
```json
      "LansaVersion": {
         "Type": "String",
         "AllowedValues": [
            "V15 GA",
            "V14 SP2"
         ],
         "Default": "V15 GA",
         "Description": "Visual LANSA Version"
      }
```
And it needs to be in the `Web Server Configuration` interface as the first parameter with a ParameterLabel the same as the description element above.

The AMI Parameter for the nested template then needs to test the `LansaVersion` parameter and look up one or other of the `AWSRegionArch2AMI*` mappings as appropriate.

And lastly, we need a mechanism to provide an AMI explicitly for use in the pipelines. Its like the imageSource parameter in the Azure template.

This requires 2 new parameters:
```json
      "ImageSource": {
         "Type": "String",
         "AllowedValues": [
            "Marketplace",
            "Custom"
         ],
         "Default": "Marketplace",
         "Description": "Location from where the image must be picked"
      },
      "AMIId": {
         "Type": "String",
         "AllowedValues": [
            "Marketplace",
            "Custom"
         ],
         "Default": "",
         "Description": "The AMI Id of the custom image. Not required when Image Source is set to Marketplace"
      }
```

And the parameters added to the `Web Server Configuration` interface as follows (including `LansaVersion`):
```json
         {
           "Label" : { "default":"Web Server Configuration" },
           "Parameters" : [ 
               "LansaVersion",
               "11WebserverOSVersion",
               "ImageSource",
               "AMIId",
               "11WebServerInstanceTyp", 
               "12WebServerMaxConnec", 
               "18WebServerCapacity" 
            ]
         },
```

And this is added to the `ParameterLabels` (including `LansaVersion`):
```
         "LansaVersion" :  { "default" :  "Visual LANSA Version"},
         "ImageSource" :  { "default" :  "Image Source"},
         "AMIId" :  { "default" :  "AMI Id"}
```

**Comment by VarunChopraAccolite** [comment]
Hi @robe070
I will sync up with the team on the provided feedback and keep you posted, also can we track it as part of template CD pipeline.

**Comment by robe070** [comment]
I've added it to AWS templates and left it in AWS Images for the moment as the code has not been merged yet as the PR was closed by @praveen-acc

**Comment by vamshi-accolite** [comment]
The issue has been tested as part of CI pipeline and looks good. If there are any issues, let us know.

**Comment by robe070** [comment]
Names of Win2019 images say Win2016. Description is correct because that is picked up from AWS parent image:
![image](https://user-images.githubusercontent.com/4089160/102552951-2cb3d100-4116-11eb-9b61-7d55c6a63e30.png)
cc: @VarunChopraAccolite

**Comment by robe070** [comment]
Win2012 removed from requirement
