### ISSUE TITLE
Create AWS template CD pipeline

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#82]
Implement a pipeline to test the deployment of the AWS templates through the AWS Marketplace process. Similar functionality to the existing Azure Template CD pipeline is required.

**Comment by robe070** [comment]
Note that the base image id for AWS is `w12r2d-14-2` (Azure was `lansa-scalable-license-14-2`). All other base Image Ids are the same on AWS as for Azure. This effects the AWS Image and AWS template CI and CD pipeline parameters too.

**Comment by robe070** [comment]
Stage 1 of this pipeline is essentially just testing the shoe sizes. This is a simple matter of creating a stack based on each Shoe Size template and the mandatory parameters - in other words, use the default settings in the template.

A PR has been raised for the Shoe Sizes - lansa/aws-templates#8
You can refer to the merge branch to build the CI that packages together the new templates and then `release` that CI run to the CD run. The branch **may** be called `pr/n8_support/scalable`. Thats the name that Git Extensions gives the branch when it pulls the PR down.

N.B. Each stack should be a parallel job which creates just 1 stack. See the recently updated Azure Template CD pipeline. If resource limits are exceeded inform me immediately and I'll get the limit extended. Its usually very quick - under an hour.

**Comment by robe070** [comment]
I have given the user AzureDevOps, known as AWSDevOps in the pipeline, access to resources in `us-east-2` for the purpose of the 'US Region' test.

And the structure of these tests needs to be different because the publishing process is different. This only makes a difference to the naming. Stage 2 and Stage 3 are currently named 'Production...'. Change them to 'Preview'. And then add a Stage 4 which is like Stage 2 - name it 'Production Stage' and then a Stage 5 (also just a waiting intervention stage) which is 'Production Manual Tests' as a reminder and record that manual test were performed on the templates that are now in production.
cc: @VarunChopraAccolite

**Comment by robe070** [comment]
@srinivasp898 You also need to handle the cookbooks git repo branch here in the CD pipeline the same way that I've instructed you to do so in the CI pipeline. There is just one difference - the branch will be different at different stages. So, have two variables
`CookbooksBranchPreview - patch/paas` and `CookbooksBranchProduction = support/scalable`. So the Shoe Size upload & tests use the former and the production upload & tests use the latter.

**Comment by srinivasp898** [comment]
updated variables in parameter's for deploy cfn template tasks in shoe size(CookbooksBranchPreview - patch/paas) and production stage(CookbooksBranchProduction = support/scalable)  , please let me know if any changes required

**Comment by robe070** [comment]
can't see any changes for this either. Do you need a call to make it clear?

**Comment by srinivasp898** [comment]
I have updated in variablegroups>defaultbranch
![image](https://user-images.githubusercontent.com/73096247/102455774-28c87600-4066-11eb-8d71-abf69adeb24e.png)
i used above parameter's in deploy cfn template task parameter's as below for CookbooksBranchPreview .
![image](https://user-images.githubusercontent.com/73096247/102455970-8066e180-4066-11eb-88ae-aee130d55f9c.png)
![image](https://user-images.githubusercontent.com/73096247/102456042-9674a200-4066-11eb-9fb5-0c8c9a7db43e.png)
i used above parameter's in deploy cfn template task parameter's as below for CookbooksBranchProduction
![image](https://user-images.githubusercontent.com/73096247/102456233-d9367a00-4066-11eb-92eb-3c5c0b001303.png)
![image](https://user-images.githubusercontent.com/73096247/102456310-f23f2b00-4066-11eb-8143-85061307879c.png)

**Comment by robe070** [comment]
good to see it in the template params, but the upload is still incorrect, and maybe other places. There should be NO explicit reference to a branch in ANY tasks. Like this needs to be changed:
![image](https://user-images.githubusercontent.com/4089160/102459358-98a42400-4099-11eb-94d1-dfde95ba2426.png)

**Comment by srinivasp898** [comment]
updated in s3 bucket task parameter   as below in cd pipeline. please let me know if any changes required
![image](https://user-images.githubusercontent.com/73096247/102464655-a2666100-4072-11eb-91bd-8a05ac169ef1.png)
![image](https://user-images.githubusercontent.com/73096247/102464897-fa9d6300-4072-11eb-8839-c1384ed6e5f0.png)

**Comment by robe070** [comment]
Double check everything, then tell me its done



Warm regards



*Rob Goodridge *| CloudArchitect | *LANSA Product Centre*



*From:* srinivasp898 <notifications@github.com>
*Sent:* Thu, 17 December 2020 7:51 PM
*To:* robe070/cookbooks <cookbooks@noreply.github.com>
*Cc:* Rob Goodridge <robert.goodridge@lansa.com.au>; Author <
author@noreply.github.com>
*Subject:* Re: [robe070/cookbooks] Create AWS template CD pipeline (#82)



updated in s3 bucket task parameter as below in cd pipeline. please let me
know if any changes required
[image: image]
<https://user-images.githubusercontent.com/73096247/102464655-a2666100-4072-11eb-91bd-8a05ac169ef1.png>
[image: image]
<https://user-images.githubusercontent.com/73096247/102464897-fa9d6300-4072-11eb-8839-c1384ed6e5f0.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/robe070/cookbooks/issues/82#issuecomment-747301761>, or
unsubscribe

**Comment by robe070** [comment]
I changed the default cookbooks repo to patch/paas.

Also added the VPC params to the template parameters

**Comment by robe070** [comment]
And I've fixed up the template - its already uploaded. Use it directly.
![image](https://user-images.githubusercontent.com/4089160/102561682-68a46180-4129-11eb-9f32-b67bc4b515af.png)

**Comment by robe070** [comment]
The version test is failing. Talk to the Image CI/CD devs to get some help, maybe @praveen-acc ?
cc: @VarunChopraAccolite 

Note once the latest Template CI build is complete, the CD VPC test should pass.

Need some urgent attention to this pipeline.

**Comment by robe070** [comment]
It looks to me like the Image CI pipeline is NOT using the SKU variable group and thats whats causing the version mismatch in the template CD pipeline. So its the Image CI pipeline that needs to be fixed.
@praveen-acc @SakshamAccolite @srinivasp898 @VarunChopraAccolite

**Comment by robe070** [comment]
I think the variable groups are not being used the most efficient way. The current structure is how Azure pipelines have been structured. It would be better if teh variable group version number variable and pipeline version number variable were the same name so that they can be overwritten if necessary - like in the Image CI. And in the case of the Build Release Images pipeline, not specify the pipeline variables so that the variable group value is used instead. Then the Image and Template pipelines will be automatically in sync.

For now, the variable group values need to be set to 1. I'm doing that now. @VarunChopraAccolite

**Comment by srinivasp898** [comment]
Hi Rob I updated regular expression to get child stack in test image version task as build is failing sometimes , and running again to make sure everything working.

**Comment by robe070** [comment]
Thanks for keeping me informed.

I have modified the pipeline stage order and added a stage at the beginning to make it clear a merge is required.

Also added a stage after preview. We do actually need one to test that AWS modifications to our templates are correct. And that they have moved all templates successfully.

We will need to repeat the regression tests from the first set of tests (Because we must confirm all the templates are present and work), but with different location for the templates. The location will be a bucket and folder provided by AWS that will need to be updated in pipeline variables.
$BucketNamePreview
$FolderNamePreview

Similarly for Production:
$BucketNameProduction
$FolderNameProduction

Each of the Preview tests will be run in a different region. Choose whatever set of regions.

Same for Production. All tests to be run in another set of different regions.

I have not copied the preview and production stages from the regression test. I though it best to wait until that is all proven to work correctly. So the 2 current stages of Preview Tests and Production Tests need to be expanded out into multiple stages like the regression test.

N.B. There may be a single value for the S3 Bucket and Folder to be used in both Preview and Production.

@VarunChopraAccolite

**Comment by robe070** [comment]
You won't be able to test the Preview Test stages nor Production Test Stages until we receive the template location. But as they are copies of a working set of regression tests, we should be quite confident that they will work.

So no hurry to implement this part - make sure the regression tests are working properly first.

**Comment by robe070** [comment]
The Shoe Sizes are being changed from 5 separate templates to a single template with a parameter to select the Shoe Size. See here:
https://github.com/robe070/cookbooks/issues/112

So the `Dev & Test Shoe Size Stage` and the `Standard Shoe Size stage` in this image need to be changed to use the new template name and add the appropriate new `StackType` parameter value:
![image](https://user-images.githubusercontent.com/4089160/106418572-c6f38c80-64aa-11eb-9e86-91d8d150eac7.png)

**Comment by robe070** [comment]
The manual Preview Stage and the manual Production stage need to describe that the appropriate Pipeline Variable Bucket and Folder names, as described in an earlier post above, are updated with the correct location.
