### ISSUE TITLE
Create AWS image CD pipeline

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#83]
Implement a pipeline to test the deployment of the AWS images through the AWS Marketplace process. Similar functionality to the existing Azure Images CD pipeline is required.

**Comment by robe070** [comment]
Note that the base image id for AWS is `w12r2d-14-2` (Azure was `lansa-scalable-license-14-2`). All other base Image Ids are the same on AWS as for Azure. This effects the AWS Image and AWS template CI and CD pipeline parameters too.

**Comment by robe070** [comment]
@srinivasp898 nobody is assigned, so nobody receives my comments :(
@VarunChopraAccolite 
The AWS images need to be in `us-east-1` to be uploaded to AWS Marketplace. Please add the last step of the AWS Image CD pipeline to copy each of the 6 images to us-east-1 and save the target AMI IDs as artefacts for submission to AWS MP.

**Comment by VarunChopraAccolite** [comment]
Hi @SakshamAccolite and @praveen-acc 
Please add a new stage to upload the AWS image CD to US-East-1 and save the target AMI Ids

**Comment by VarunChopraAccolite** [comment]
hi @robe070 
do we need to test all the shoe sizes along with the templates testing for each image or we are fine with having a template test for each image?
cc: @praveen-acc @SakshamAccolite

**Comment by robe070** [comment]
Each Shoe Size in the regression test should use a different Win/LANSA version combination. That will test 5 of them as I think there are 5 shoe sizes. Thats enough.

**Comment by praveen-acc** [comment]
@robe070 But we can't pass custom image in shoe size template right?

**Comment by robe070** [comment]
I was making the comment about **template** release CD pipeline. So ignore it.

Correct. Just use the Master template. Then you can specify Custom. 

And use the same parameters for each image. Defaults will be fine. Just need to use the different custom image each time

**Comment by robe070** [comment]
When the image is copied the Name value must be set to the AMI Name. See some of the previous had copied AMIs in us-east-1:
![image](https://user-images.githubusercontent.com/4089160/102552318-1ce7bd00-4115-11eb-92c1-1bdf33b92060.png)

**Comment by robe070** [comment]
If a Release is re-done, with the same AMI, does the AMI copy succeed when the AMI is already there?

**Comment by robe070** [comment]
@VarunChopraAccolite

**Comment by robe070** [comment]
The `Save copied ami` task is trying to resolve the AMI ID. Why is it not done in the Copy AMI to us-east-1 task where it is already displayed in the log? And whilst you are about it, annotate the log output for that task so its clear where the image is. Like
```
ap-southeast-2 AMI-7327832987932
us-east-1 AMI-998765432
```

**Comment by robe070** [comment]
And this single file of artefacts that I am expecting to get must work correctly when re-run. I'm thinking that the AMI-ID and description can be saved in an image specific file, and then the 6 image-specific files are consolidated into 1 in a post-job task - when all images pass the tests and all have been copied.

**Comment by robe070** [comment]
Note that the template parameters for the other 5 images are incorrect - git branch not specified. Looks like they can simply be copied from the first image's parameters.

**Comment by robe070** [comment]
I've linked the variable group Template Parameters to pick up the VPC values

**Comment by praveen-acc** [comment]
> The `Save copied ami` task is trying to resolve the AMI ID. Why is it not done in the Copy AMI to us-east-1 task where it is already displayed in the log? And whilst you are about it, annotate the log output for that task so its clear where the image is. Like
> 
> ```
> ap-southeast-2 AMI-7327832987932
> us-east-1 AMI-998765432
> ```

I can't get the new ami -id in the first task, as it's region was set to ap-southeast-2. I don't know wether "Set-Default AWSRegion" will work. So I created a new task  with different region.

**Comment by praveen-acc** [comment]
> And this single file of artefacts that I am expecting to get must work correctly when re-run. I'm thinking that the AMI-ID and description can be saved in an image specific file, and then the 6 image-specific files are consolidated into 1 in a post-job task - when all images pass the tests and all have been copied.

I already added a task where it will take all ami-id from publish tasks and merge them. But Varun said we can't publish artefacts in release pipeline. Even if I add the publish artefact task, he said there is no way to access them like in ci pipeleine. So I logged them out in that task.
![Screenshot (119)](https://user-images.githubusercontent.com/70358924/102562588-69bf9980-40fd-11eb-9d35-1e930ae8f712.png)

**Comment by robe070** [comment]
So what is the purpose of `Save copied ami`? Why do you care about the region? You have the AMI in the previous task.

**Comment by robe070** [comment]
I presume you can write to a file. And then log them all in `Log AMI artefacts`

**Comment by robe070** [comment]
> I can't get the new ami -id in the first task, as it's region was set to ap-southeast-2. I don't know wether "Set-Default AWSRegion" will work. So I created a new task with different region.

But its LOGGED. So you have it. What is outputting that? Capture it.

**Comment by praveen-acc** [comment]
> So what is the purpose of `Save copied ami`? Why do you care about the region? You have the AMI in the previous task.

When we copy the ami in Copy ami to us-east -1 task, it's ami-id changes in the us-east-1. To know what is that ami, I have to change region in aws creds. So I created a new task in which region is us-east-1 in aws creds. If I don't change region it can't access ami-id's in us-east -1

**Comment by robe070** [comment]
You're not getting it. The AMI is in the LOG. So you can just use that.

**Comment by praveen-acc** [comment]
> > I can't get the new ami -id in the first task, as it's region was set to ap-southeast-2. I don't know wether "Set-Default AWSRegion" will work. So I created a new task with different region.
> 
> But its LOGGED. So you have it. What is outputting that? Capture it.

I didn't log anything in copy ami  to us task. I have logged it in Save copied ami task.

**Comment by robe070** [comment]
Look at the log. Its there!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

This is probably whats outputting it:
Copy-EC2Image -SourceRegion ap-southeast-2 -SourceImageId $amiID -Region us-east-1 -Name $imageName

So,
$TargetAMIId = Copy-EC2Image -SourceRegion ap-southeast-2 -SourceImageId $amiID -Region us-east-1 -Name $imageName

and you have it!!!!!

**Comment by robe070** [comment]
Not so simple. It returns an object. You'll need to work out the sub field to reference.
See [here](https://docs.aws.amazon.com/powershell/latest/reference/items/Copy-EC2Image.html)

**Comment by praveen-acc** [comment]
Oh! sorry. Even then if I need to add tag called Name,  region needs to change

**Comment by robe070** [comment]
Still capture the AMI. Write it to a file. Use that to tag the name.

**Comment by praveen-acc** [comment]
@robe070 If I try to save the ami-id in the $(Build.ArtifactStagingDirectory)/copy-w12..txt  it is showing error that it can't recognize it.  I used the exact same command like in image ci pipeline. So, bringing all ami's together will not be possible. What do you suggest?

**Comment by VarunChopraAccolite** [comment]
Hi @praveen-acc 
Upload to s3

**Comment by robe070** [comment]
@praveen-acc @SakshamAccolite 
template params look as if they have individually had the VPC settings added and not used the git branch.

The entire set of params from Win2012-14-2 can be copied and pasted into the other 5. Simple.

Who is going to do this? Please put your hand up.

**Comment by SakshamAccolite** [comment]
Doing @robe070

**Comment by praveen-acc** [comment]
@robe070 2 url tests are not only failing in win 2019 but also 2016.

**Comment by robe070** [comment]
I tested win2016 and it was fine. So, double check in the AWS Console that the AMI that is being used by the VMs is Win2016. Check the description.

**Comment by praveen-acc** [comment]
@robe070  I checked the logs and checked the ami description in aws console , Webserver is win 2016 only.

**Comment by robe070** [comment]
Strange. My test worked. Maybe it wasn't a Win2016 image I tested. Maybe AMI Ids are mixed up in the templte. 

It will need to wait until I'm back.
