### ISSUE TITLE
Allow an existing VPC to be selected or add a new VPC

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#85]
Allow the user to choose an existing VPC or add a new VPC with appropriate access control lists (ACLs) and security groups.

The pattern to use would include something like the following:
``` json
"Description": "This template creates a Multi-AZ, multi-subnet VPC infrastructure with managed NAT gateways in the public subnet for each Availability Zone. You can also create additional private subnets with dedicated custom network access control lists (ACLs). If you deploy the Quick Start in a region that doesn't support NAT gateways, NAT instances are deployed instead. **WARNING** This template creates AWS resources. You will be billed for the AWS resources used if you create a stack from this template. QS(0027)",
  "Parameters": {
    "CreateVPC": {
      "AllowedValues": [
        "Yes",
        "No"
      ],
      "Type": "String",
      "Default": "Yes"
    },
    "CurrentVPC": {
      "Description": "List of VPC",
      "Type": "List<AWS::EC2::VPC::Id>"
    }
  }
}
```
The parameter “CreateVPC” is to let user select whether to create a new VPC, and second parameter “CurrentVPC” is to let user select VPC if they don’t want to create a new VPC. And then you use condition in Resource for VPC (when CreateVPC is Yes). 

The new vpc resource must use a nested template in a manner similar to the patterns shown in these templates, except also add in the ability to use an existing VPC and thus make the new VPC template conditional:
[ec2-autoscale.json.txt](https://github.com/robe070/cookbooks/files/5290260/ec2-autoscale.json.txt)
[aws-vpc.json.txt](https://github.com/robe070/cookbooks/files/5290253/aws-vpc.json.txt)

**Comment by ajitesh-s** [comment]
Hi @robe070 ,the PR is merged for adding (using a nested template) or using an existing Vpc. It is also tested as part of the CD Pipeline and the job is successfully completed. Attaching the ss for reference. 
![Vpcjob](https://user-images.githubusercontent.com/71516648/102478608-cb432200-4083-11eb-896e-c363a433c314.JPG)

**Comment by robe070** [comment]
Hi Ajitesh

So it seems that if the parameter type is special, that a value MUST be provided. And providing a default value in a region for which the default does not exist is hidden from the user.

So I think some template descriptions need to change, if I'm correct.

Do my new descriptions make sense? Are they true?

```
        "CurrentVPC": {
            "Description": "Existing VPC id. If creating a new VPC you must still select a valid existing VPC in order to pass CFT validation.",
            "Type": "AWS::EC2::VPC::Id",
        },
        "AvailabilityZones": {
            "Description": "List of Availability Zones to use for the subnets in the VPC. Note: The logical order is preserved. If using an existing VPC you must still select a valid Availability Zone in order to pass CFT validation.",
            "Type": "List<AWS::EC2::AvailabilityZone::Name>",
        },
        "NumberOfAZs": {
            "Default": "3",
            "Description": "Number of Availability Zones to use in the VPC. This must match your selections in the list of Availability Zones parameter.",
            "Type": "String",
            "AllowedValues": [
                "2",
                "3"
            ]
        },
        "DBSubnetGroupName": {
            "Description": "The name of the DB Subnet Group which needs to be provided if using an existing VPC. DB Subnet Group Name can be checked in the Amazon RDS console in the Subnet section along with the VPC in which it was created.",
            "Type": "String",
        },
        "ELBSubnetIds": {
            "Description": "List of Subnet IDs for ELB which needs to be provided if using an existing VPC. If you are creating a new VPC you must still select a valid subnet in order to pass CFT validation.",
            "Type": "List<AWS::EC2::Subnet::Id>",
        },
```

**Comment by ajitesh-s** [comment]
Hi Rob,
Yes the new descriptions makes sense. I will make these changes and test the templates.
