### ISSUE TITLE
Marketplace Certification feedback

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#89]
![image](https://user-images.githubusercontent.com/4089160/93843940-f9ac9d80-fcde-11ea-9990-8caf5a79e2a9.png)

![image](https://user-images.githubusercontent.com/4089160/93843957-04673280-fcdf-11ea-83b3-50fcbacb44be.png)

![image](https://user-images.githubusercontent.com/4089160/93843973-1052f480-fcdf-11ea-87ea-25e8ad69fa30.png)

![image](https://user-images.githubusercontent.com/4089160/93843990-1c3eb680-fcdf-11ea-8d7d-29c0cbd0e53f.png)

**Comment by robe070** [comment]
@VarunChopraAccolite @ashutosh-kumar1 
When are you planning on working on this issue?

**Comment by ashutosh-kumar1** [comment]
Hi @robe070,
I will work on it today.

**Comment by ashutosh-kumar1** [comment]
Hi @robe070,
We went over the comments. We are currently working on the 1st and 2nd comments mentioned in the screenshot above. Please provide some clarity on the 3rd and 4th comments. Do they mean adding the files in the solution template? We are not sure how we can use them if added to the solution template. It might require additional changes in the pipeline once the changes in the zip file are done.

**Comment by robe070** [comment]
The files must be uploaded as part of the Solution Template submission. And the template needs to refer to them within the package. I do not know how to refer to an artifact in a package. You will need to work it out.

**Comment by ashutosh-kumar1** [comment]
@robe070, We get an understanding to use the nested templates and hope that the same logic should work in our case. We see two examples for using the relative path to access the resources in the Azure QuickStart Template Github repository. We see that the provided solutions will be tested only post-deployment (using relative URLs). It will fast forward if we can get confirmation from the Microsoft team.
We plan to introduce the ArtifactLocation parameter and modify GitRefreshUri and to test the changes locally. We will use the default values as per the marketplace requirements. For testing it locally we can pass these values using the test.parameters.json file.

# References

## MSDN Link
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/linked-templates

## Examples
1. Concat with the relative URL to access assets

"uri": "[concat(parameters('artifactsBaseUrl'),'/vnet-with-dns-server.json')]",

We see artifactsBaseUrl is not set

```
"artifactsBaseUrl": {
"type": "string",
"metadata": {
"description": "Base URL for Marketplace",
"artifactsBaseUrl": ""
}
},
```

https://github.com/Azure/azure-quickstart-templates/blob/ddeb6c5b92f46c064f1a443c796235f0f01f6f24/create-hpc-cluster/mainTemplate.json#L389

2. Concat using the deployment template link properties

"[uri(parameters('_artifactsLocation'), concat('scripts/copyfilefromazure.sh'))]"



```
"_artifactsLocation": {
"type": "string",
"metadata": {
"description": "The base URI where artifacts required by this template are located. When the template is deployed using the accompanying scripts, a private location in the subscription will be used and this value will be automatically generated."
},
"defaultValue": "[deployment().properties.templateLink.uri]"
},
```

https://github.com/lansa/azure-quickstart-templates/blob/support/scalable/100-marketplace-sample/azuredeploy.json#L396



Note: We didn't find a concrete example with the zip file, though we did find related examples to use the assets and scripts prior to solution template zip deployment.

**Comment by robe070** [comment]
Quickstart templates are not Solution templates. There is no script run with Solution Templates. There may be an answer somewhere and I cannot find it. And the reviewer of the template is not responding to questions.

So, I have reviewed the details of uri usage in the template. The script `git-pull.ps1` is already located on the VM and does not need to be downloaded. Where `gitRefreshName` is used directly in the `CustomScriptExtension` script, replace it with the local path `c:\\lansa\\scripts\\git-pull.ps1`. So, the variables `gitRefreshName`, `gitRefreshUri` and `gitRepo` can be deleted. Also delete the reference to `gitRefreshUri` in the two `CustomScriptExtension` resources. 

And that leaves the `msiURL` default value. Which we can solve the way @ashutosh-kumar1 suggested. That is, don't have a default value.

**Comment by ashutosh-kumar1** [comment]
@robe070, Review comments incorporated and verified by running it locally.
The changes for createUIDefinition file verified at:
https://portal.azure.com/?feature.customPortal=false#blade/Microsoft_Azure_CreateUIDef/SandboxBlade
Also, the arm ttk testing verified locally.
PR raised: https://github.com/lansa/azure-quickstart-templates/pull/14
