### ISSUE TITLE
Install LANSA licenses from PFX files in AWS Parameter Store

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#91]
Install the LANSA Licenses in the AWS images.

The files now exist in the AWS Parameter Store. Each license is in a separate parameter named after the name of the file. So the file `LANSAScalableLicense.pfx` is stored as the parameter `LANSAScalableLicense.pfx`. Its value is in Base64. Its also encrypted using a KMS key, but that is transparent to the user, provided the permissions are set up correctly.

When creating the EC2 instance, an IAM Role must be specified of `LansaInstalls_ec2`. This Role has permission to read the encrypted parameters.

The code to read the parameter and write to a file is as follows:

``` Powershell
$LicenseName = 'LANSAScalableLicense.pfx'
$ReconstitutedFile = 'c:\temp\$LicenseName'
$Parameter = get-ssmparameter -Name $LicenseName -WithDecryption $true
[IO.File]::WriteAllBytes($ReconstitutedFile, [Convert]::FromBase64String($Parameter.Value)
```

The old method of installing the private key was to copy a file from the local machine to the Image, install that certificate and then obliterate the file from the Image's disk. See `bake-ide-ps1` lines 726 - 731 for the client code. And in `install-lansa-scalable.ps1` lines 88-95 for the code run on the image. That code presumes the pfx files exist. So, the code above must be inserted before the file is required. And repeated for `LANSAIntegratorLicense.pfx`. In fact the best place for the new code looks to be in the CreateLicence function. Make sure all the code is conditioned for AWS and that Azure still works correctly.

You will also require the $LicenseKeyPassword which is stored in the Parameter `LicensePrivateKeyPassword`

**Comment by robe070** [comment]
"@Robert Goodridge For Issue #91, do I also need to retrieve LansaDevelopmentLicense from aws parameter store?"

No you do not.

**Comment by praveen-acc** [comment]
> "@robert Goodridge For Issue #91, do I also need to retrieve LansaDevelopmentLicense from aws parameter store?"
> 
> No you do not.

 So, I need to only worry about lines 726-731 in "bake-ide-ami.ps1" ?  LansaIntegratorLicense is also being used in line 684 where $InstallIDE -eq $true .

**Comment by robe070** [comment]
> > "@robert Goodridge For Issue #91, do I also need to retrieve LansaDevelopmentLicense from aws parameter store?"
> > No you do not.
> 
> So, I need to only worry about lines 726-731 in "bake-ide-ami.ps1" ? LansaIntegratorLicense is also being used in line 684 where $InstallIDE -eq $true .

Correct.

**Comment by robe070** [comment]
`$InstallIDE` type build is not being used currently and will probably never be used again. Just focus on what you are building now.
