### ISSUE TITLE
Make use of the DB VMSS in the work load

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#92]
Always use Standard Load Balancer and make both VMSS use the one LB

Currently there are two Basic Load Balancers; one for each VMSS.

This Issue is to change the LB to Standard and have the ONE LB direct traffic to BOTH VMSS.

**Comment by robe070** [comment]
The simplest way to create an example stack is to start with the Marketplace LANSA Scalable Stack:
https://azuremarketplace.microsoft.com/en-ca/marketplace/apps/lansa.lansa-scalable-stack-win-2019?tab=Overview
This uses mainTemplate.json.

**Comment by Arshpreet1002** [comment]
Please close this Ticket as testing is done and PR is merged.

**Comment by robe070** [comment]
RDP into port 50000 and 50002 is to the same VM. Please fix it.

**Comment by Arshpreet1002** [comment]
Hi Rob Please close the issue.

**Comment by robe070** [comment]
@anant-k-agrawal The template has been rejected due to new ARM TTK tests. I've modified the Azure Template CI pipeline to use the latest tests. Who will work on this?

**Comment by ganeshk146** [comment]
@robe070 ,

I am not understanding what is the issue? Can you please elaborate

**Comment by robe070** [comment]
Are you an Azure template programmer?

**Comment by ganeshk146** [comment]
@robe070 ,

Let me see If I can resolve this or not.

**Comment by robe070** [comment]
https://dev.azure.com/VisualLansa/Lansa%20Azure%20Scalable%20License%20Images/_build/results?buildId=1186&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=5fd232ee-0bcd-5c4f-9e6b-7e96853085e6
So you have 6 CreateUIDefinition files to fix and the two templates described in the errors above

**Comment by robe070** [comment]
Note that for some reason an error message is missing from the LANSA pipeline output for the CreateUIDefinition
```
##[error]        Could not find stackType in outputs
```

So you will need to add StackType to the outputs even though we do not use it.

**Comment by robe070** [comment]
And the maximum lengths of the passwords should be set to 128

**Comment by ganeshk146** [comment]
> Note that for some reason an error message is missing from the LANSA pipeline output for the CreateUIDefinition
> 
> ```
> ##[error]        Could not find stackType in outputs
> ```
> 
> So you will need to add StackType to the outputs even though we do not use it.

This is fixed

**Comment by ganeshk146** [comment]
> And the maximum lengths of the passwords should be set to 128

I try to see why it is failing with arm-ttk tests and found this is a bug and it is fixed on `15-May-2021`
Here is the URL https://github.com/Azure/arm-ttk/pull/359/files 

I think we are using the old code of arm-ttk , here is the example of file contents which is old 
https://dev.azure.com/VisualLansa/Lansa%20Azure%20Scalable%20License%20Images/_build/results?buildId=1193&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=617275de-25b5-5eb9-57d8-e307df514032&l=272

To fix the problem we need to take the latest version of the code, Not sure how to merge it, any Idea Rob?

**Comment by robe070** [comment]
> I try to see why it is failing with arm-ttk tests and found this is a bug and it is fixed on `15-May-2021` Here is the URL https://github.com/Azure/arm-ttk/pull/359/files

This explains why the messages in Marketplace are confusing. There is one that says the ARM TTK tests pass. And then I got a later message with the failures you have been investigating. The pull request you identified is sufficient evidence to determine that there is nothing for us to do.

We are using the latest ARM TTK that has been released for public consumption. So where does that leave us? I think our only option is to disable the ARM TTK test for this run. Then obtain the build artifacts for testing in the CD pipeline and switch the test back on, hoping that its fixed before we run it again. I will raise a support request to have the public package updated. (And I won't be commenting further today as I'm on sick leave with back pain - painful to sit here typing)

**Comment by robe070** [comment]
@ganeshk146 
You need to fix these errors still:
```
##[error]        Depends On Must not start with [concat(
##[error]        Found hardcoded reference to core.windows.net Index:10729
```

**Comment by robe070** [comment]
@ganeshk146 
I've deleted a comment hence you probably got an error when clicking on a link.

I don't like the validation options available. If we specify the directory to test as the top level directory, as we have been, then one UI is tested in a subdir and the maintemplate.json at the top level and ALL template files in sub directories. And we do not want to test those template in the sub directories as we do not submit them to Azure Marketplace. The errors that are currently surfacing in those templates do not need to be addressed.

If we change the test directory to one of the subdirs like createUIDefinitionDev, then that directory MUST contain a mainTemplate.json, and it MUST match the UI. So that means copying the mainTemplate.json into EVERY sub directory that has a UI. And I've done that. But that means that the UI in the top level - the custom UI is not tested. Just 1 file not tested and none of the templates that we do not need tested. I think this is the best option. It does mean that mainTemplate.json must be copied into each of the sub directories when it changes.

So, please rebase my changes into your branch, and run the test to demonstrate that you've fixed all the issues except for the maximum length.

**Comment by robe070** [comment]
And I'm not clear why you changed the repo to your repo? Why not just raise a PR?

**Comment by ganeshk146** [comment]
> And I'm not clear why you changed the repo to your repo? Why not just raise a PR?

As I said in slack before raising PR I want to make sure my changes are correct after running tests, I am still working on the "depends on" error I haven't got a solution yet.
<img width="1166" alt="Screenshot 2021-10-11 at 8 56 43 AM" src="https://user-images.githubusercontent.com/72592790/136729080-6464afb8-1e1d-4f56-b488-9c3629dd456a.png">

**Comment by robe070** [comment]
I shouldn't have raised the thumb. I believe you have now changed the security and it will require changing back. If you had simply raised a PR and got it working that way then the only difference is I'm seeing each commit. Its only necessary to do this for CD pipelines, because they do not have a PR option, and in that case we have a strategy for that of changing variable names and/or switching between 2 artifacts rather than having to input the security values again and risk getting them wrong.

And, I've altered the CI pipeline so that the templates that were raising the `depends on` error are no longer tested. And I've added some necessary change to the repo. So please follow the instructions from my second last comment above. Rebase, etc.

**Comment by ganeshk146** [comment]
I am confused now, I will do one thing, 
1. I will revert my changes in the pipeline.
2. I will raise a PR for my fixes.
Is that ok?

**Comment by ganeshk146** [comment]
Can we have a short call?

**Comment by robe070** [comment]
yes. send an invite in Slack

**Comment by ganeshk146** [comment]
@robe070 ,

The fix for dependsOn error is https://github.com/lansa/azure-quickstart-templates/pull/32
